/**
 * P7.1 Tests — PromotionLadder
 *
 * Tests: register, getLevel, promote chain (GENERATED→CORE),
 * promote at CORE → failure, demote chain (CORE→GENERATED),
 * demote at GENERATED → failure, canDeploy threshold,
 * listByLevel, DNA-3 compliance.
 */

import { DataProcessResult } from '../../src/kernel/data-process-result';
import {
  PromotionLadder,
  PromotionLevel,
  PROMOTION_LEVEL_NAMES,
} from '../../src/guardrails/promotion-ladder';

describe('PromotionLadder', () => {
  let ladder: PromotionLadder;

  beforeEach(() => {
    ladder = new PromotionLadder();
  });

  describe('register + getLevel', () => {
    it('should register at GENERATED by default', () => {
      ladder.register('F166');
      expect(ladder.getLevel('F166')).toBe(PromotionLevel.GENERATED);
    });

    it('should register at specified level', () => {
      ladder.register('F166', PromotionLevel.MINIMAL);
      expect(ladder.getLevel('F166')).toBe(PromotionLevel.MINIMAL);
    });

    it('should return GENERATED for unregistered artifacts', () => {
      expect(ladder.getLevel('F999')).toBe(PromotionLevel.GENERATED);
    });

    it('should track artifact with has()', () => {
      ladder.register('F166');
      expect(ladder.has('F166')).toBe(true);
      expect(ladder.has('F999')).toBe(false);
    });
  });

  describe('promote', () => {
    it('should promote GENERATED → INJECTED', () => {
      ladder.register('F166');
      const result = ladder.promote('F166');
      expect(result.isSuccess).toBe(true);
      expect(result.data).toBe('INJECTED');
      expect(ladder.getLevel('F166')).toBe(PromotionLevel.INJECTED);
    });

    it('should promote INJECTED → MINIMAL', () => {
      ladder.register('F166', PromotionLevel.INJECTED);
      const result = ladder.promote('F166');
      expect(result.isSuccess).toBe(true);
      expect(result.data).toBe('MINIMAL');
    });

    it('should promote MINIMAL → CORE', () => {
      ladder.register('F166', PromotionLevel.MINIMAL);
      const result = ladder.promote('F166');
      expect(result.isSuccess).toBe(true);
      expect(result.data).toBe('CORE');
    });

    it('should fail to promote at CORE', () => {
      ladder.register('F166', PromotionLevel.CORE);
      const result = ladder.promote('F166');
      expect(result.isSuccess).toBe(false);
      expect(result.errorCode).toBe('ALREADY_CORE');
    });

    it('should promote full chain GENERATED → CORE', () => {
      ladder.register('F166');
      ladder.promote('F166'); // INJECTED
      ladder.promote('F166'); // MINIMAL
      ladder.promote('F166'); // CORE
      expect(ladder.getLevel('F166')).toBe(PromotionLevel.CORE);
    });

    it('should return DataProcessResult (DNA-3)', () => {
      ladder.register('F166');
      const result = ladder.promote('F166');
      expect(result).toBeInstanceOf(DataProcessResult);
    });
  });

  describe('demote', () => {
    it('should demote CORE → MINIMAL', () => {
      ladder.register('F166', PromotionLevel.CORE);
      const result = ladder.demote('F166');
      expect(result.isSuccess).toBe(true);
      expect(result.data).toBe('MINIMAL');
    });

    it('should demote MINIMAL → INJECTED', () => {
      ladder.register('F166', PromotionLevel.MINIMAL);
      const result = ladder.demote('F166');
      expect(result.isSuccess).toBe(true);
      expect(result.data).toBe('INJECTED');
    });

    it('should fail to demote at GENERATED', () => {
      ladder.register('F166');
      const result = ladder.demote('F166');
      expect(result.isSuccess).toBe(false);
      expect(result.errorCode).toBe('ALREADY_GENERATED');
    });

    it('should return DataProcessResult (DNA-3)', () => {
      ladder.register('F166', PromotionLevel.CORE);
      const result = ladder.demote('F166');
      expect(result).toBeInstanceOf(DataProcessResult);
    });
  });

  describe('canDeploy', () => {
    it('should return false for GENERATED (below default MINIMAL threshold)', () => {
      ladder.register('F166');
      expect(ladder.canDeploy('F166')).toBe(false);
    });

    it('should return false for INJECTED (below MINIMAL)', () => {
      ladder.register('F166', PromotionLevel.INJECTED);
      expect(ladder.canDeploy('F166')).toBe(false);
    });

    it('should return true for MINIMAL (meets default threshold)', () => {
      ladder.register('F166', PromotionLevel.MINIMAL);
      expect(ladder.canDeploy('F166')).toBe(true);
    });

    it('should return true for CORE (exceeds threshold)', () => {
      ladder.register('F166', PromotionLevel.CORE);
      expect(ladder.canDeploy('F166')).toBe(true);
    });

    it('should respect custom minimum level', () => {
      ladder.register('F166', PromotionLevel.INJECTED);
      expect(ladder.canDeploy('F166', PromotionLevel.INJECTED)).toBe(true);
      expect(ladder.canDeploy('F166', PromotionLevel.MINIMAL)).toBe(false);
    });
  });

  describe('getLevelName', () => {
    it('should return level name string', () => {
      ladder.register('F166', PromotionLevel.MINIMAL);
      expect(ladder.getLevelName('F166')).toBe('MINIMAL');
    });
  });

  describe('listByLevel', () => {
    it('should list artifacts at a specific level', () => {
      ladder.register('F166', PromotionLevel.GENERATED);
      ladder.register('F167', PromotionLevel.MINIMAL);
      ladder.register('F168', PromotionLevel.GENERATED);
      const generated = ladder.listByLevel(PromotionLevel.GENERATED);
      expect(generated).toHaveLength(2);
      expect(generated).toContain('F166');
      expect(generated).toContain('F168');
    });

    it('should return empty for level with no artifacts', () => {
      expect(ladder.listByLevel(PromotionLevel.CORE)).toHaveLength(0);
    });
  });

  describe('count + clear', () => {
    it('should track count', () => {
      ladder.register('F166');
      ladder.register('F167');
      expect(ladder.count).toBe(2);
    });

    it('should clear all', () => {
      ladder.register('F166');
      ladder.clear();
      expect(ladder.count).toBe(0);
    });
  });

  describe('PROMOTION_LEVEL_NAMES', () => {
    it('should have names for all 4 levels', () => {
      expect(PROMOTION_LEVEL_NAMES[PromotionLevel.GENERATED]).toBe('GENERATED');
      expect(PROMOTION_LEVEL_NAMES[PromotionLevel.INJECTED]).toBe('INJECTED');
      expect(PROMOTION_LEVEL_NAMES[PromotionLevel.MINIMAL]).toBe('MINIMAL');
      expect(PROMOTION_LEVEL_NAMES[PromotionLevel.CORE]).toBe('CORE');
    });
  });
});
