#!/usr/bin/env python3
"""
phase-c12-real-fork-execution.py

Phase C12 — Real fork execution for FLOW-01 portability.

Per FORK-EXECUTION-DIRECTIVE.md and FLOW-01-PORTABILITY-PLAN.md §13 First Next Action.
Closes ciEvidence (workflowRunUrl + workflowConclusion="success") for all three
tenant fork repos, unblocking TIER-D promotion.

What this script does — in this exact order, no stops, no questions:

  1. Read each tenant's github_token + github_org_name from Vault
     (canonical paths: secret/data/{tenantId}/{key} via VAULT_API_PREFIX=/v1/secret).
     Token IS the Vault-stored value — never the session credential (BC-012).

  2. Run the existing flow-01-fork-and-install-test.py harness to assemble a
     self-contained fork directory (server/src/{kernel,fabrics/interfaces,
     freedom,engine/flows/user-registration} + package.json + tsconfig.json
     + jest.config.js). Same code as Phase C11, retained.

  3. Inject `.github/workflows/flow-ci.yml` — the per-tenant CI workflow that
     runs `npm install && npx tsc --noEmit && npx jest` inside the tenant
     repo on push. This is what proves R4 (independent test) at the tenant level.

  4. For each tenant:
       a. Create GitHub repo `{orgName}/{tenantId}--user-registration` (private)
          via `gh repo create`. If it already exists, reuse.
       b. git init + commit + push from the assembled fork directory.
       c. Set `XIIGEN_TENANT_ID` GitHub Actions secret in the repo.
       d. Poll /repos/{org}/{repo}/actions/runs until conclusion (max 300s).
       e. Capture {repoUrl, workflowRunUrl, workflowConclusion} into ciEvidence.

  5. Write a JSON summary to docs/portability/flow-01/c12-real-fork-evidence.json
     so the human-driven STATE.json update has a structured input.

The only valid stop conditions (per FORK-EXECUTION-DIRECTIVE):
  - `gh auth token` returns empty                 -> exit 10
  - Vault not reachable / token missing           -> exit 11
  - `git push` fails for any tenant               -> exit 12
  - CI poll times out (300s) for any tenant       -> record "TIMEOUT_PENDING"
                                                    in ciEvidence (Rule F-7
                                                    carry-forward), continue.

Everything else: keep going. No question to operator.

Usage:
    python scripts/portability/phase-c12-real-fork-execution.py
    python scripts/portability/phase-c12-real-fork-execution.py --skip-create
        (reuse existing tenant repos; only re-push + re-poll)
    python scripts/portability/phase-c12-real-fork-execution.py --tenant acme-pro-members
        (single-tenant run for debugging)
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
HARNESS = REPO_ROOT / "scripts" / "portability" / "flow-01-fork-and-install-test.py"
EVIDENCE_OUT = REPO_ROOT / "docs" / "portability" / "flow-01" / "c12-real-fork-evidence.json"

DEFAULT_TENANTS = ["acme-pro-members", "northwind-guild", "tessera-collective"]
FLOW_SLUG = "user-registration"
FLOW_ID = "FLOW-01"
VAULT_ADDR = os.environ.get("VAULT_ADDR", "http://localhost:8200")
VAULT_TOKEN = os.environ.get("VAULT_TOKEN", "xiigen-dev-root-token")
POLL_TIMEOUT_SEC = 300
POLL_INTERVAL_SEC = 5


# ── Tenant CI workflow injected into every fork repo ──
TENANT_CI_WORKFLOW = """\
# Generated by phase-c12-real-fork-execution.py — Phase C12, FLOW-01.
# Per TENANT-CICD-CONNECTION-GUIDANCE-v1.0 §"What 'properly configured CI/CD'
# means in XIIGen". Runs INSIDE the tenant's forked repo on every push,
# proving R4 (Independent test) at the tenant level — not on the platform repo.

name: XIIGen Flow CI - {flow_slug}

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  flow-ci:
    name: Standalone flow test - {flow_slug}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: "24"

      - name: Install
        # npm install (not `npm ci`) — the fork ships package.json only;
        # package-lock.json is generated on first install in the tenant repo.
        run: npm install --no-fund --no-audit

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: Test
        run: npx jest --forceExit
        env:
          XIIGEN_TENANT_ID: ${{{{ secrets.XIIGEN_TENANT_ID }}}}
"""


# ────────────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────────────


def log(msg: str) -> None:
    print(f"[c12] {msg}", flush=True)


def run(cmd: list[str], *, cwd: Path | None = None, check: bool = True,
        capture: bool = False, env: dict | None = None) -> subprocess.CompletedProcess:
    """Wrapper around subprocess.run with consistent logging."""
    proc = subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        check=False,
        capture_output=capture,
        text=True,
        env=env,
    )
    if check and proc.returncode != 0:
        log(f"FAIL ({proc.returncode}): {' '.join(cmd)}")
        if capture:
            log(f"stdout: {proc.stdout[:500]}")
            log(f"stderr: {proc.stderr[:500]}")
        raise SystemExit(proc.returncode)
    return proc


def vault_read(path: str, key: str) -> str | None:
    """Read a secret value from Vault KV v2.
    URL matches VaultSecretsManagerService: /v1/secret/data/{path}.
    Returns the inner key value or None if missing.
    """
    url = f"{VAULT_ADDR}/v1/secret/data/{path}"
    req = urllib.request.Request(url, headers={"X-Vault-Token": VAULT_TOKEN})
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            body = json.load(resp)
            return body.get("data", {}).get("data", {}).get(key)
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return None
        raise
    except Exception as e:
        log(f"vault_read error for {path}: {e}")
        return None


def gh(args: list[str], *, capture: bool = True) -> subprocess.CompletedProcess:
    """Run a `gh` command. Authentication comes from `gh auth login` already done."""
    return run(["gh"] + args, capture=capture, check=False)


def gh_api(endpoint: str, *, method: str = "GET", body: dict | None = None) -> dict | list | None:
    """Call gh api with JSON body. Returns parsed JSON or None on 404."""
    cmd = ["gh", "api", endpoint, "--method", method]
    if body is not None:
        cmd += ["--input", "-"]
    proc = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        input=json.dumps(body) if body else None,
        check=False,
    )
    if proc.returncode != 0:
        if "404" in proc.stderr or "Not Found" in proc.stderr:
            return None
        log(f"gh api {endpoint} ({method}) FAILED: {proc.stderr[:300]}")
        return None
    if not proc.stdout.strip():
        return None
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError:
        return None


# ────────────────────────────────────────────────────────────────────────
# Stage 1 — Verify environment + read Vault credentials
# ────────────────────────────────────────────────────────────────────────


def verify_env_and_creds(tenants: list[str]) -> dict[str, dict[str, str]]:
    """Returns: {tenantId: {github_token, github_org_name}}. Exits on failure."""
    log("Stage 1 — environment + Vault credentials")

    # gh auth check (FORK-EXECUTION-DIRECTIVE valid stop #1)
    gh_token = run(["gh", "auth", "token"], capture=True).stdout.strip()
    if not gh_token:
        log("FAIL: gh auth token is empty. Run `gh auth login`.")
        raise SystemExit(10)
    log(f"gh auth: OK (token len {len(gh_token)})")

    # Vault reachability check (FORK-EXECUTION-DIRECTIVE valid stop #2)
    try:
        with urllib.request.urlopen(f"{VAULT_ADDR}/v1/sys/health", timeout=5) as resp:
            assert resp.status == 200
        log(f"vault: OK at {VAULT_ADDR}")
    except Exception as e:
        log(f"FAIL: Vault not reachable at {VAULT_ADDR}: {e}")
        raise SystemExit(11)

    # Per-tenant credential read
    creds: dict[str, dict[str, str]] = {}
    for tid in tenants:
        token = vault_read(tid + "/github_token", "github_token")
        org = vault_read(tid + "/github_org_name", "github_org_name")
        if not token or not org:
            log(f"FAIL: missing Vault creds for {tid} (token={bool(token)}, org={bool(org)})")
            raise SystemExit(11)
        log(f"vault[{tid}]: token len {len(token)}, org={org}")
        creds[tid] = {"github_token": token, "github_org_name": org}
    return creds


# ────────────────────────────────────────────────────────────────────────
# Stage 2 — Assemble the fork directory via the existing harness
# ────────────────────────────────────────────────────────────────────────


def assemble_fork() -> Path:
    """Run the C11 harness with --keep to produce a self-contained fork tmp dir.
    Returns the path to the assembled fork.

    The harness logs the tmp dir path to stdout. We parse it.
    """
    log("Stage 2 — assemble fork via flow-01-fork-and-install-test.py")
    tmp_root = Path(tempfile.mkdtemp(prefix="c12-fork-"))
    log(f"  tmp_root={tmp_root}")
    proc = run(
        ["python", str(HARNESS), "--keep", "--tmp-dir", str(tmp_root)],
        check=False,
        capture=True,
    )
    if proc.returncode != 0:
        log(f"harness FAILED (exit {proc.returncode}):")
        log(proc.stdout[-2000:] if proc.stdout else "")
        log(proc.stderr[-1000:] if proc.stderr else "")
        raise SystemExit(proc.returncode)
    log("  harness PASS — fork is self-contained (npm install + tsc + jest green)")

    # The harness creates `<tmp_root>/flow-01-fork-<ts>/` as the assembled
    # fork (with its own package.json + tsconfig + jest.config + server/).
    # Find that subdir — it's where we inject the CI workflow and what we
    # copy per-tenant.
    candidates = sorted(tmp_root.glob("flow-01-fork-*"))
    if not candidates:
        log(f"FAIL: harness produced no flow-01-fork-* dir under {tmp_root}")
        raise SystemExit(4)
    fork = candidates[-1]
    log(f"  fork assembled at {fork}")

    # Inject the per-tenant CI workflow
    workflows = fork / ".github" / "workflows"
    workflows.mkdir(parents=True, exist_ok=True)
    (workflows / "flow-ci.yml").write_text(TENANT_CI_WORKFLOW.format(flow_slug=FLOW_SLUG))
    log(f"  injected .github/workflows/flow-ci.yml")
    return fork


# ────────────────────────────────────────────────────────────────────────
# Stage 3 — Per-tenant: create repo + push + set secret + poll CI
# ────────────────────────────────────────────────────────────────────────


def fork_one_tenant(
    tenant_id: str,
    creds: dict[str, str],
    fork_dir: Path,
    skip_create: bool = False,
) -> dict[str, object]:
    """Returns ciEvidence dict per the guidance schema."""
    org = creds["github_org_name"]
    token = creds["github_token"]
    repo_name = f"{tenant_id}--{FLOW_SLUG}"
    full_name = f"{org}/{repo_name}"
    log(f"--- tenant: {tenant_id} -> {full_name} ---")

    # Step a — create repo (or reuse)
    if not skip_create:
        check = gh_api(f"repos/{full_name}")
        if check is None:
            log(f"  creating repo {full_name}")
            create_proc = run(
                ["gh", "repo", "create", full_name, "--private",
                 "--description", f"FLOW-01 fork for tenant {tenant_id} — Phase C12 portability evidence"],
                capture=True,
                check=False,
            )
            if create_proc.returncode != 0:
                log(f"  repo create FAILED: {create_proc.stderr[:300]}")
                raise SystemExit(12)
        else:
            log(f"  repo {full_name} already exists — reusing")

    repo_url = f"https://github.com/{full_name}"

    # Step b — push from a fresh per-tenant copy.
    # Each tenant gets its own copy of the assembled tree so git history is
    # tenant-scoped (forks must look independent at HEAD even though they're
    # bit-identical at v1.0.0). node_modules/ is excluded so the push stays
    # small and CI does its own `npm install` against package.json.
    tenant_work = Path(tempfile.mkdtemp(prefix=f"c12-work-{tenant_id}-"))

    def _ignore_node_modules(_src: str, names: list[str]) -> list[str]:
        skip: list[str] = []
        for n in names:
            if n in {"node_modules", ".git"}:
                skip.append(n)
            elif n.endswith(".tsbuildinfo"):
                skip.append(n)
        return skip

    shutil.copytree(fork_dir, tenant_work, dirs_exist_ok=True, ignore=_ignore_node_modules)
    # Add a .gitignore so subsequent `npm install` output is never committed.
    (tenant_work / ".gitignore").write_text(
        "node_modules/\n*.tsbuildinfo\n.DS_Store\n"
    )

    git_env = {**os.environ}
    git_env.setdefault("GIT_AUTHOR_NAME", "xiigen-portability")
    git_env.setdefault("GIT_AUTHOR_EMAIL", "portability@xiigen.local")
    git_env.setdefault("GIT_COMMITTER_NAME", "xiigen-portability")
    git_env.setdefault("GIT_COMMITTER_EMAIL", "portability@xiigen.local")

    run(["git", "init", "-q", "-b", "main"], cwd=tenant_work, env=git_env)
    run(["git", "add", "-A"], cwd=tenant_work, env=git_env)
    run(
        ["git", "commit", "-q", "-m",
         f"Initial fork: FLOW-01 user-registration v1.0.0 for {tenant_id}\n\n"
         f"Phase C12 (DEV-115) — real R2/R4 proof. Generated by\n"
         f"phase-c12-real-fork-execution.py from FLOW-01 platform-source."],
        cwd=tenant_work, env=git_env,
    )

    # Use the tenant's Vault-supplied token for the push (proves Vault path,
    # NOT session token — BC-012 anti-theater).
    push_url = f"https://x-access-token:{token}@github.com/{full_name}.git"
    run(["git", "remote", "add", "origin", push_url], cwd=tenant_work, env=git_env)

    push_proc = run(
        ["git", "push", "-u", "-f", "origin", "main"],
        cwd=tenant_work, env=git_env, capture=True, check=False,
    )
    if push_proc.returncode != 0:
        log(f"  git push FAILED: {push_proc.stderr[:300]}")
        raise SystemExit(12)

    # Capture the head SHA so the poller can match the exact run we triggered,
    # not a stale prior run the API returns first.
    head_sha = run(
        ["git", "rev-parse", "HEAD"],
        cwd=tenant_work, env=git_env, capture=True, check=False,
    ).stdout.strip()
    log(f"  pushed to {repo_url} (HEAD={head_sha[:12]})")

    # Step c — set XIIGEN_TENANT_ID secret
    secret_proc = subprocess.run(
        ["gh", "secret", "set", "XIIGEN_TENANT_ID",
         "--repo", full_name, "--body", tenant_id],
        capture_output=True, text=True, check=False,
    )
    if secret_proc.returncode != 0:
        log(f"  set-secret FAILED (non-fatal per Rule F-5): {secret_proc.stderr[:200]}")
    else:
        log(f"  XIIGEN_TENANT_ID secret set")

    # Step d — poll Actions runs, matching by head SHA so we never grab a
    # stale prior run. Workflow runs are eventually-consistent — wait until
    # one with matching head_sha appears, then wait for its conclusion.
    log(f"  polling Actions runs for head_sha={head_sha[:12]} (max {POLL_TIMEOUT_SEC}s)")
    started = time.time()
    workflow_run_url: str | None = None
    workflow_conclusion: str | None = None
    workflow_run_id: int | None = None
    while time.time() - started < POLL_TIMEOUT_SEC:
        runs = gh_api(f"repos/{full_name}/actions/runs?per_page=10")
        target = None
        if runs and runs.get("workflow_runs"):
            for run_obj in runs["workflow_runs"]:
                if run_obj.get("head_sha") == head_sha:
                    target = run_obj
                    break
        if target is not None:
            workflow_run_id = target.get("id")
            workflow_run_url = target.get("html_url")
            status = target.get("status")
            conclusion = target.get("conclusion")
            log(f"  run {workflow_run_id}: status={status} conclusion={conclusion}")
            if conclusion is not None:
                workflow_conclusion = conclusion
                break
        else:
            log(f"  no run yet for head_sha={head_sha[:12]} (waiting)")
        time.sleep(POLL_INTERVAL_SEC)

    if workflow_conclusion is None:
        workflow_conclusion = "TIMEOUT_PENDING"

    return {
        "tenantId": tenant_id,
        "repoUrl": repo_url,
        "repoFullName": full_name,
        "workflowRunUrl": workflow_run_url,
        "workflowRunId": workflow_run_id,
        "workflowConclusion": workflow_conclusion,
        "workflowRunAt": datetime.now(timezone.utc).isoformat(),
        "connectionVerifiedAt": datetime.now(timezone.utc).isoformat(),
    }


# ────────────────────────────────────────────────────────────────────────
# Main
# ────────────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tenant", action="append", default=None,
                        help="single tenant id (can be repeated). Default: all 3.")
    parser.add_argument("--skip-create", action="store_true",
                        help="reuse existing tenant repos, only re-push + re-poll")
    args = parser.parse_args()

    tenants = args.tenant or DEFAULT_TENANTS
    log(f"Phase C12 real fork execution — {len(tenants)} tenant(s): {', '.join(tenants)}")

    creds = verify_env_and_creds(tenants)
    fork_dir = assemble_fork()

    evidence: dict[str, object] = {
        "phase": "C12",
        "flowId": FLOW_ID,
        "flowSlug": FLOW_SLUG,
        "executedAt": datetime.now(timezone.utc).isoformat(),
        "executor": "phase-c12-real-fork-execution.py",
        "vaultAddr": VAULT_ADDR,
        "tenants": [],
    }

    for tid in tenants:
        result = fork_one_tenant(tid, creds[tid], fork_dir, skip_create=args.skip_create)
        evidence["tenants"].append(result)

    EVIDENCE_OUT.parent.mkdir(parents=True, exist_ok=True)
    EVIDENCE_OUT.write_text(json.dumps(evidence, indent=2))
    log(f"WROTE {EVIDENCE_OUT.relative_to(REPO_ROOT)}")

    # Summary table
    log("=" * 60)
    log(f"{'tenant':<24}{'conclusion':<18}{'run id':<12}")
    for t in evidence["tenants"]:
        log(f"{t['tenantId']:<24}{str(t['workflowConclusion']):<18}{str(t.get('workflowRunId') or '-'):<12}")
    log("=" * 60)

    all_success = all(t["workflowConclusion"] == "success" for t in evidence["tenants"])
    return 0 if all_success else 1


if __name__ == "__main__":
    sys.exit(main())
