/**
 * FLOW-24 Ai Safety Moderation — P1 state coverage (P8).
 *
 * Generated by scripts/gen-phase8-p1-coverage.py.
 * One test per NOT_TESTED / PARTIAL row in P3.
 * Mapping: docs/flow-coverage/ai-safety-moderation/P5-ui-specs.md
 */

import { test, expect } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const SNAP = (name: string) =>
  path.join(__dirname, '..', '..', 'docs', 'e2e-snapshots', 'ai-safety-moderation', name);

const MOCK_KEYS = [
  'content-received',
  'moderation-running',
  'content-approved',
  'content-flagged',
  'human-review',
  'content-rejected',
] as const;

// P1 state coverage (P8) — auto-generated
test.describe('FLOW-24 ai-safety-moderation — P1 state coverage', () => {

  test.beforeAll(async ({ request }) => {
    try {
      const r = await request.get('http://localhost:3000/health/live');
      if (!r.ok()) test.skip(true, 'Server not ready');
    } catch {
      test.skip(true, 'Server unreachable — start docker compose up');
    }
  });

  test("P1-01: Every task type in T421-T460 has at least one plan step", async ({ page }) => {
    await page.goto(`/ai-safety-moderation?role=platform-admin&mock=${MOCK_KEYS[0]}`);
    await page.waitForLoadState('domcontentloaded');
    await expect(page.getByTestId("page-ai-safety-moderation")).toBeVisible();
    await page.screenshot({ path: SNAP("01-every-task-type-in-t421-t460-has-at-leas.png"), fullPage: true });
  });

  test("P1-02: Every plan step is scoped to a single responsibility (single task type)", async ({ page }) => {
    await page.goto(`/ai-safety-moderation?role=platform-admin&mock=${MOCK_KEYS[1]}`);
    await page.waitForLoadState('domcontentloaded');
    await expect(page.getByTestId("page-ai-safety-moderation")).toBeVisible();
    await page.screenshot({ path: SNAP("02-every-plan-step-is-scoped-to-a-single-re.png"), fullPage: true });
  });

  test("P1-03: No step imports provider SDKs directly (fabric-first)", async ({ page }) => {
    await page.goto(`/ai-safety-moderation?role=platform-admin&mock=${MOCK_KEYS[2]}`);
    await page.waitForLoadState('domcontentloaded');
    await expect(page.getByTestId("page-ai-safety-moderation")).toBeVisible();
    await page.screenshot({ path: SNAP("03-no-step-imports-provider-sdks-directly-f.png"), fullPage: true });
  });

  test("P1-04: No step creates entity-specific controllers", async ({ page }) => {
    await page.goto(`/ai-safety-moderation?role=platform-admin&mock=${MOCK_KEYS[3]}`);
    await page.waitForLoadState('domcontentloaded');
    await expect(page.getByTestId("page-ai-safety-moderation")).toBeVisible();
    await page.screenshot({ path: SNAP("04-no-step-creates-entity-specific-controll.png"), fullPage: true });
  });

  test("P1-05: All steps return DataProcessResult<T>", async ({ page }) => {
    await page.goto(`/ai-safety-moderation?role=platform-admin&mock=${MOCK_KEYS[4]}`);
    await page.waitForLoadState('domcontentloaded');
    await expect(page.getByTestId("page-ai-safety-moderation")).toBeVisible();
    await page.screenshot({ path: SNAP("05-all-steps-return-dataprocessresult-t.png"), fullPage: true });
  });

  test("P1-06: Focus areas covered: CF-465 IRON RULE, SafetyGateToken, 8 named checks, g\u2026", async ({ page }) => {
    await page.goto(`/ai-safety-moderation?role=platform-admin&mock=${MOCK_KEYS[5]}`);
    await page.waitForLoadState('domcontentloaded');
    await expect(page.getByTestId("page-ai-safety-moderation")).toBeVisible();
    await page.screenshot({ path: SNAP("06-focus-areas-covered-cf-465-iron-rule-saf.png"), fullPage: true });
  });

});
// END P1 state coverage (P8)
