/**
 * FLOW-25 Bfa Cross Flow Governance — P1 state coverage (P8).
 *
 * Generated by scripts/gen-phase8-p1-coverage.py.
 * One test per NOT_TESTED / PARTIAL row in P3.
 * Mapping: docs/flow-coverage/bfa-cross-flow-governance/P5-ui-specs.md
 */

import { test, expect } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const SNAP = (name: string) =>
  path.join(__dirname, '..', '..', 'docs', 'e2e-snapshots', 'bfa-cross-flow-governance', name);

// P1 state coverage (P8) — auto-generated
test.describe('FLOW-25 bfa-cross-flow-governance — P1 state coverage', () => {

  test.beforeAll(async ({ request }) => {
    try {
      const r = await request.get('http://localhost:3000/health/live');
      if (!r.ok()) test.skip(true, 'Server not ready');
    } catch {
      test.skip(true, 'Server unreachable — start docker compose up');
    }
  });

  test("P1-01: CHANGE-INTAKE-PARSE-001 (T375): content-addressed ingestion \u2014 parse + nor\u2026", async ({ page }) => {
    await page.goto("/admin/bfa-cross-flow-governance");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("01-change-intake-parse-001-t375-content-add.png"), fullPage: true });
    await expect(page.getByTestId("page-bfa-cross-flow-governance")).toBeVisible();
  });

  test("P1-02: BLAST-RADIUS-TRAVERSAL-001 (T380): transitive graph traversal with cycle-\u2026", async ({ page }) => {
    await page.goto("/admin/bfa-cross-flow-governance");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("02-blast-radius-traversal-001-t380-transiti.png"), fullPage: true });
    await expect(page.getByTestId("page-bfa-cross-flow-governance")).toBeVisible();
  });

  test("P1-04: CROSS-TENANT-GUARD-001 (T387): cross-tenant conflict detection with expli\u2026", async ({ page }) => {
    await page.goto("/admin/bfa-cross-flow-governance");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("03-cross-tenant-guard-001-t387-cross-tenant.png"), fullPage: true });
    await expect(page.getByTestId("page-bfa-cross-flow-governance")).toBeVisible();
  });

});
// END P1 state coverage (P8)
