/**
 * FLOW-00 Bundle Activation — P1 state coverage (P8).
 *
 * Generated by scripts/gen-phase8-p1-coverage.py.
 * One test per NOT_TESTED / PARTIAL row in P3.
 * Mapping: docs/flow-coverage/bundle-activation/P5-ui-specs.md
 */

import { test, expect } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const SNAP = (name: string) =>
  path.join(__dirname, '..', '..', 'docs', 'e2e-snapshots', 'bundle-activation', name);
const SERVER_BASE =
  process.env['API_BASE_URL'] ?? `http://localhost:${process.env['SERVER_PORT'] ?? '3000'}`;

// P1 state coverage (P8) — auto-generated
test.describe('FLOW-00 bundle-activation — P1 state coverage', () => {

  test.beforeAll(async ({ request }) => {
    try {
      const r = await request.get(`${SERVER_BASE}/health/live`);
      if (!r.ok()) test.skip(true, 'Server not ready');
    } catch {
      test.skip(true, 'Server unreachable — start docker compose up');
    }
  });

  test("P1-01: BundleValidator \u2014 processing step entered via system-initialized", async ({ page }) => {
    await page.goto("/admin/bundle-activation?role=platform-admin&mock=validation-pending");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("01-bundlevalidator-processing-step-entered.png"), fullPage: true });
    await expect(page.getByTestId("page-bundle-activation")).toBeVisible();
  });

  test("P1-02: BundleActivationOrchestrator \u2014 processing step entered via system-initial\u2026", async ({ page }) => {
    await page.goto("/admin/bundle-activation?role=platform-admin&mock=dry-run-running");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("02-bundleactivationorchestrator-processing.png"), fullPage: true });
    await expect(page.getByTestId("page-bundle-activation")).toBeVisible();
  });

  test("P1-03: BundleStatusTracker \u2014 processing step entered via system-initialized", async ({ page }) => {
    await page.goto("/admin/bundle-activation?role=platform-admin&mock=active");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("03-bundlestatustracker-processing-step-ente.png"), fullPage: true });
    await expect(page.getByTestId("page-bundle-activation")).toBeVisible();
  });

  test("P1-04: BundleActivationRequested \u2192 BundleValidator when  (emits )", async ({ page }) => {
    await page.goto("/admin/bundle-activation?role=platform-admin&mock=validation-pending");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("04-bundleactivationrequested-bundlevalidato.png"), fullPage: true });
    await expect(page.getByTestId("page-bundle-activation")).toBeVisible();
  });

  test("P1-05: BundleValidator \u2192 BundleActivationOrchestrator when valid === true (emits\u2026", async ({ page }) => {
    await page.goto("/admin/bundle-activation?role=platform-admin&mock=dry-run-running");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("05-bundlevalidator-bundleactivationorchestr.png"), fullPage: true });
    await expect(page.getByTestId("page-bundle-activation")).toBeVisible();
  });

  test("P1-06: BundleValidator \u2192 BundleValidationCompleted when  (emits )", async ({ page }) => {
    await page.goto("/admin/bundle-activation?role=platform-admin&mock=active");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("06-bundlevalidator-bundlevalidationcomplete.png"), fullPage: true });
    await expect(page.getByTestId("page-bundle-activation")).toBeVisible();
  });

  test("P1-07: BundleActivationOrchestrator \u2192 BundleActivated when  (emits )", async ({ page }) => {
    await page.goto("/admin/bundle-activation?role=platform-admin&mock=active");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("07-bundleactivationorchestrator-bundleactiv.png"), fullPage: true });
    await expect(page.getByTestId("page-bundle-activation")).toBeVisible();
  });

  test("P1-08: flow-lifecycle.regenerated \u2192 BundleStatusTracker when  (emits )", async ({ page }) => {
    await page.goto("/admin/bundle-activation?role=platform-admin&mock=restored");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("08-flow-lifecycle-regenerated-bundlestatust.png"), fullPage: true });
    await expect(page.getByTestId("page-bundle-activation")).toBeVisible();
  });

  test("P1-09: BundleStatusTracker \u2192 BundleDegraded when versionBelowMinimum (emits )", async ({ page }) => {
    await page.goto("/admin/bundle-activation?role=platform-admin&mock=degraded");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("09-bundlestatustracker-bundledegraded-when.png"), fullPage: true });
    await expect(page.getByTestId("page-bundle-activation")).toBeVisible();
  });

  test("P1-10: BundleStatusTracker \u2192 BundleRestored when allVersionsMet (emits )", async ({ page }) => {
    await page.goto("/admin/bundle-activation?role=platform-admin&mock=restored");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("10-bundlestatustracker-bundlerestored-when.png"), fullPage: true });
    await expect(page.getByTestId("page-bundle-activation")).toBeVisible();
  });

});
// END P1 state coverage (P8)
