/**
 * FLOW-05 Completion Gamification — P1 state coverage (P8).
 *
 * Generated by scripts/gen-phase8-p1-coverage.py.
 * One test per NOT_TESTED / PARTIAL row in P3.
 * Mapping: docs/flow-coverage/completion-gamification/P5-ui-specs.md
 */

import { test, expect } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const SNAP_SUFFIX = process.env.E2E_SNAPSHOT_SUFFIX ?? '';
const withSnapshotSuffix = (name: string) => {
  if (!SNAP_SUFFIX) return name;
  const ext = path.extname(name);
  const base = name.slice(0, name.length - ext.length);
  return `${base}${SNAP_SUFFIX}${ext}`;
};
const SNAP = (name: string) =>
  path.join(
    __dirname,
    '..',
    '..',
    'docs',
    'e2e-snapshots',
    'completion-gamification',
    withSnapshotSuffix(name),
  );
const SERVER_HEALTH_URL =
  process.env.SERVER_HEALTH_URL ??
  `http://localhost:${process.env.SERVER_PORT ?? '3000'}/health/live`;

// P1 state coverage (P8) — auto-generated
test.describe('FLOW-05 completion-gamification — P1 state coverage', () => {

  test.beforeAll(async ({ request }) => {
    try {
      const r = await request.get(SERVER_HEALTH_URL);
      if (!r.ok()) test.skip(true, 'Server not ready');
    } catch {
      test.skip(true, 'Server unreachable - start docker compose up');
    }
  });

  test("P1-01: CompletionRecorder \u2014 orchestration step entered via LessonCompletionSubmi\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("01-completionrecorder-orchestration-step-en.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-02: PointsCalculator \u2014 processing step entered via CompletionRecorded event (\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("02-pointscalculator-processing-step-entered.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-03: LedgerUpdater \u2014 processing step entered via PointsAwarded event", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("03-ledgerupdater-processing-step-entered-vi.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-04: LevelUpChecker \u2014 processing step entered via LedgerUpdated event", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("04-levelupchecker-processing-step-entered-v.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-05: AchievementGate \u2014 processing step entered via LevelUpChecked event", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("05-achievementgate-processing-step-entered.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-06: SocialShareGate \u2014 processing step entered via AchievementUnlocked event (\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("06-socialsharegate-processing-step-entered.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-07: StreakManager \u2014 processing step entered via CompletionRecorded event (tim\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("07-streakmanager-processing-step-entered-vi.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-08: LearningFlowCompleted \u2014 orchestration step entered via AllGamificationCom\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("08-learningflowcompleted-orchestration-step.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-09: LessonCompletionSubmitted \u2192 CompletionRecorder when  (emits xiigen.comple\u2026", async ({ page }) => {
    await page.goto("/lessons/complete");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("09-lessoncompletionsubmitted-completionreco.png"), fullPage: true });
    await expect(page.getByTestId("gamification-feedback")).toBeVisible();
  });

  test("P1-10: CompletionRecorder \u2192 PointsCalculator when  (emits xiigen.completion-gami\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("10-completionrecorder-pointscalculator-when.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-11: CompletionRecorder \u2192 StreakManager when streak branch (emits xiigen.compl\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("11-completionrecorder-streakmanager-when-st.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-12: PointsCalculator \u2192 LedgerUpdater when  (emits xiigen.completion-gamificat\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("12-pointscalculator-ledgerupdater-when-emit.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-13: LedgerUpdater \u2192 LevelUpChecker when  (emits xiigen.completion-gamificatio\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("13-ledgerupdater-levelupchecker-when-emits.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-14: LevelUpChecker \u2192 AchievementGate when  (emits xiigen.completion-gamificat\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("14-levelupchecker-achievementgate-when-emit.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-15: AchievementGate \u2192 SocialShareGate when achievement unlocked (emits xiigen\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("15-achievementgate-socialsharegate-when-ach.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-16: SocialShareGate \u2192 LearningFlowCompleted when  (emits xiigen.completion-ga\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("16-socialsharegate-learningflowcompleted-wh.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-17: StreakManager \u2192 LearningFlowCompleted when  (emits xiigen.completion-gami\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("17-streakmanager-learningflowcompleted-when.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

  test("P1-18: LearningFlowCompleted \u2192 LearningFlowCompleted when terminal (emits xiigen\u2026", async ({ page }) => {
    await page.goto("/gamification");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("18-learningflowcompleted-learningflowcomple.png"), fullPage: true });
    await expect(page.getByTestId("gamification-dashboard")).toBeVisible();
  });

});
// END P1 state coverage (P8)
