/**
 * FLOW-37 Design System Governance — P1 state coverage (P8).
 *
 * Generated by scripts/gen-phase8-p1-coverage.py.
 * One test per NOT_TESTED / PARTIAL row in P3.
 * Mapping: docs/flow-coverage/design-system-governance/P5-ui-specs.md
 */

import { test, expect } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const SNAP = (name: string) =>
  path.join(__dirname, '..', '..', 'docs', 'e2e-snapshots', 'design-system-governance', name);

// P1 state coverage (P8) — auto-generated
test.describe('FLOW-37 design-system-governance — P1 state coverage', () => {
  test.setTimeout(60_000);

  test.beforeAll(async ({ request }) => {
    try {
      const r = await request.get('http://localhost:3000/health/live');
      if (!r.ok()) test.skip(true, 'Server not ready');
    } catch {
      test.skip(true, 'Server unreachable — start docker compose up');
    }
  });

  test("P1-02: HYBRID-GENESIS-PROMPT-001: Stack-aware genesis prompt builder with incomp\u2026", async ({ page }) => {
    await page.goto('/admin/design-system-governance?role=platform-admin&hideChrome=1', {
      waitUntil: 'domcontentloaded',
    });
    await expect(page.getByTestId('platform-ops-design-system-governance')).toBeVisible();
    await expect(page.getByTestId('stack-porting-screen')).toBeVisible();
    await page.screenshot({ path: SNAP("01-hybrid-genesis-prompt-001-stack-aware-ge.png"), fullPage: true });
  });

  test("P1-03: DESIGN-DEBT-ANALYSIS-001: Design complexity scoring with token consistenc\u2026", async ({ page }) => {
    await page.goto('/admin/design-system-governance?role=platform-admin&hideChrome=1', {
      waitUntil: 'domcontentloaded',
    });
    await expect(page.getByTestId('platform-ops-design-system-governance')).toBeVisible();
    await expect(page.getByTestId('reports-section')).toBeVisible();
    await page.screenshot({ path: SNAP("02-design-debt-analysis-001-design-complexi.png"), fullPage: true });
  });

});
// END P1 state coverage (P8)
