/**
 * FLOW-23 Form Builder Templates — P1 state coverage (P8).
 *
 * Generated by scripts/gen-phase8-p1-coverage.py.
 * One test per NOT_TESTED / PARTIAL row in P3.
 * Mapping: docs/flow-coverage/form-builder-templates/P5-ui-specs.md
 */

import { test, expect, type Page } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const SNAP = (name: string) =>
  path.join(__dirname, '..', '..', 'docs', 'e2e-snapshots', 'form-builder-templates', name);

async function openTemplateBuilder(page: Page) {
  await page.goto('/form-templates', { waitUntil: 'domcontentloaded', timeout: 60_000 });
  await expect(page.getByTestId('page-templatebuilder.tsx')).toBeVisible({ timeout: 60_000 });
  await page.waitForLoadState('networkidle', { timeout: 10_000 }).catch(() => undefined);
}

// P1 state coverage (P8) — auto-generated
test.describe('FLOW-23 form-builder-templates — P1 state coverage', () => {

  test.describe.configure({ timeout: 60_000 });

  test.beforeAll(async ({ request }) => {
    try {
      const r = await request.get('http://localhost:3000/health/live');
      if (!r.ok()) test.skip(true, 'Server not ready');
    } catch {
      test.skip(true, 'Server unreachable — start docker compose up');
    }
  });

  test("P1-01: Every task type in T381-T420 has at least one plan step", async ({ page }) => {
    await openTemplateBuilder(page);
    await page.screenshot({ path: SNAP("01-every-task-type-in-t381-t420-has-at-leas.png"), fullPage: true });
    await expect(page.getByTestId("page-templatebuilder.tsx")).toBeVisible();
  });

  test("P1-02: Every plan step is scoped to a single responsibility (single task type)", async ({ page }) => {
    await openTemplateBuilder(page);
    await page.screenshot({ path: SNAP("02-every-plan-step-is-scoped-to-a-single-re.png"), fullPage: true });
    await expect(page.getByTestId("page-templatebuilder.tsx")).toBeVisible();
  });

  test("P1-03: No step imports provider SDKs directly (fabric-first)", async ({ page }) => {
    await openTemplateBuilder(page);
    await page.screenshot({ path: SNAP("03-no-step-imports-provider-sdks-directly-f.png"), fullPage: true });
    await expect(page.getByTestId("page-templatebuilder.tsx")).toBeVisible();
  });

  test("P1-04: No step creates entity-specific controllers", async ({ page }) => {
    await openTemplateBuilder(page);
    await page.screenshot({ path: SNAP("04-no-step-creates-entity-specific-controll.png"), fullPage: true });
    await expect(page.getByTestId("page-templatebuilder.tsx")).toBeVisible();
  });

  test("P1-05: All steps return DataProcessResult<T>", async ({ page }) => {
    await openTemplateBuilder(page);
    await page.screenshot({ path: SNAP("05-all-steps-return-dataprocessresult-t.png"), fullPage: true });
    await expect(page.getByTestId("page-templatebuilder.tsx")).toBeVisible();
  });

  test("P1-06: Focus areas covered: form builder, template gallery, submission pipeline", async ({ page }) => {
    await openTemplateBuilder(page);
    await page.screenshot({ path: SNAP("06-focus-areas-covered-form-builder-templat.png"), fullPage: true });
    await expect(page.getByTestId("page-templatebuilder.tsx")).toBeVisible();
  });

});
// END P1 state coverage (P8)
