/**
 * FLOW-17 Freelancer Marketplace — P1 state coverage (P8).
 *
 * Generated by scripts/gen-phase8-p1-coverage.py.
 * One test per NOT_TESTED / PARTIAL row in P3.
 * Mapping: docs/flow-coverage/freelancer-marketplace/P5-ui-specs.md
 */

import { test, expect } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const SNAP = (name: string) =>
  path.join(__dirname, '..', '..', 'docs', 'e2e-snapshots', 'freelancer-marketplace', name);

// P1 state coverage (P8) — auto-generated
test.describe('FLOW-17 freelancer-marketplace — P1 state coverage', () => {

  test.beforeAll(async ({ request }) => {
    try {
      const r = await request.get('http://localhost:3000/health/live');
      if (!r.ok()) test.skip(true, 'Server not ready');
    } catch {
      test.skip(true, 'Server unreachable — start docker compose up');
    }
  });

  test("P1-01: Every task type in T229-T245 has at least one plan step", async ({ page }) => {
    await page.goto("/gigs/post?hideChrome=1", { waitUntil: 'domcontentloaded' });
    await expect(page.getByTestId("gig-posting-page")).toBeVisible();
    await page.screenshot({ path: SNAP("01-every-task-type-in-t229-t245-has-at-leas.png"), fullPage: true });
    await expect(page.getByTestId("gig-posting-page")).toBeVisible();
  });

  test("P1-02: Every plan step is scoped to a single responsibility (single task type)", async ({ page }) => {
    await page.goto("/gigs/post?hideChrome=1", { waitUntil: 'domcontentloaded' });
    await expect(page.getByTestId("gig-posting-page")).toBeVisible();
    await page.screenshot({ path: SNAP("02-every-plan-step-is-scoped-to-a-single-re.png"), fullPage: true });
    await expect(page.getByTestId("gig-posting-page")).toBeVisible();
  });

  test("P1-03: No step imports provider SDKs directly (fabric-first)", async ({ page }) => {
    await page.goto("/gigs/post?hideChrome=1", { waitUntil: 'domcontentloaded' });
    await expect(page.getByTestId("gig-posting-page")).toBeVisible();
    await page.screenshot({ path: SNAP("03-no-step-imports-provider-sdks-directly-f.png"), fullPage: true });
    await expect(page.getByTestId("gig-posting-page")).toBeVisible();
  });

  test("P1-04: No step creates entity-specific controllers", async ({ page }) => {
    await page.goto("/gigs/post?hideChrome=1", { waitUntil: 'domcontentloaded' });
    await expect(page.getByTestId("gig-posting-page")).toBeVisible();
    await page.screenshot({ path: SNAP("04-no-step-creates-entity-specific-controll.png"), fullPage: true });
    await expect(page.getByTestId("gig-posting-page")).toBeVisible();
  });

  test("P1-05: All steps return DataProcessResult<T>", async ({ page }) => {
    await page.goto("/gigs/post?hideChrome=1", { waitUntil: 'domcontentloaded' });
    await expect(page.getByTestId("gig-posting-page")).toBeVisible();
    await page.screenshot({ path: SNAP("05-all-steps-return-dataprocessresult-t.png"), fullPage: true });
    await expect(page.getByTestId("gig-posting-page")).toBeVisible();
  });

  test("P1-06: Focus areas covered: N-step LIFO compensation, escrow ledger, deliverable\u2026", async ({ page }) => {
    await page.goto("/gigs/post?hideChrome=1", { waitUntil: 'domcontentloaded' });
    await expect(page.getByTestId("gig-posting-page")).toBeVisible();
    await page.screenshot({ path: SNAP("06-focus-areas-covered-n-step-lifo-compensa.png"), fullPage: true });
    await expect(page.getByTestId("gig-posting-page")).toBeVisible();
  });

});
// END P1 state coverage (P8)
