/**
 * FLOW-07 Friend Request Social Feed — P1 state coverage (P8).
 *
 * Generated by scripts/gen-phase8-p1-coverage.py.
 * One test per NOT_TESTED / PARTIAL row in P3.
 * Mapping: docs/flow-coverage/friend-request-social-feed/P5-ui-specs.md
 */

import { test, expect } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const SNAP = (name: string) =>
  path.join(__dirname, '..', '..', 'docs', 'e2e-snapshots', 'friend-request-social-feed', name);
const SERVER_PORT = process.env.SERVER_PORT ?? '3000';

// P1 state coverage (P8) — auto-generated
test.describe('FLOW-07 friend-request-social-feed — P1 state coverage', () => {

  test.beforeAll(async ({ request }) => {
    try {
      const r = await request.get(`http://localhost:${SERVER_PORT}/health/live`);
      if (!r.ok()) test.skip(true, 'Server not ready');
    } catch {
      test.skip(true, 'Server unreachable — start docker compose up');
    }
  });

  test("P1-01: FriendRequestProcessor \u2014 orchestration step entered via POST /friends/req\u2026", async ({ page }) => {
    await page.goto("/friend-requests");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("01-friendrequestprocessor-orchestration-ste.png"), fullPage: true });
    await expect(page.getByTestId("friend-request-page")).toBeVisible();
  });

  test("P1-02: FriendRequestResponder \u2014 orchestration step entered via FriendRequestSent\u2026", async ({ page }) => {
    await page.goto("/connections");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("02-friendrequestresponder-orchestration-ste.png"), fullPage: true });
    await expect(page.getByTestId("connections-page")).toBeVisible();
  });

  test("P1-03: ConnectionGraphWriter \u2014 orchestration step entered via FriendRequestAccep\u2026", async ({ page }) => {
    await page.goto("/connections");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("03-connectiongraphwriter-orchestration-step.png"), fullPage: true });
    await expect(page.getByTestId("connections-page")).toBeVisible();
  });

  test("P1-04: FeedItemGenerator \u2014 ai_generation step entered via ConnectionEstablished\u2026", async ({ page }) => {
    await page.goto("/connections");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("04-feeditemgenerator-ai-generation-step-ent.png"), fullPage: true });
    await expect(page.getByTestId("connections-page")).toBeVisible();
  });

  test("P1-05: FeedScorer \u2014 ai_generation step entered via FeedItemGenerated event (scor\u2026", async ({ page }) => {
    await page.goto("/connections");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("05-feedscorer-ai-generation-step-entered-vi.png"), fullPage: true });
    await expect(page.getByTestId("connections-page")).toBeVisible();
  });

  test("P1-06: FeedDeliveryOrchestrator \u2014 orchestration step entered via FeedItemScored\u2026", async ({ page }) => {
    await page.goto("/connections");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("06-feeddeliveryorchestrator-orchestration-s.png"), fullPage: true });
    await expect(page.getByTestId("connections-page")).toBeVisible();
  });

  test("P1-07: SocialNotificationDispatcher \u2014 orchestration step entered via ConnectionE\u2026", async ({ page }) => {
    await page.goto("/connections");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("07-socialnotificationdispatcher-orchestrati.png"), fullPage: true });
    await expect(page.getByTestId("connections-page")).toBeVisible();
  });

  test("P1-08: SocialGraphAnalytics \u2014 observability step entered via Graph topology anal\u2026", async ({ page }) => {
    await page.goto("/social-graph");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("08-socialgraphanalytics-observability-step.png"), fullPage: true });
    await expect(page.getByTestId("social-graph-page")).toBeVisible();
  });

  test("P1-09: FriendRequestRequested \u2192 FriendRequestProcessor when  (emits xiigen.frien\u2026", async ({ page }) => {
    await page.goto("/friend-requests");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("09-friendrequestrequested-friendrequestproc.png"), fullPage: true });
    await expect(page.getByTestId("friend-request-page")).toBeVisible();
  });

  test("P1-10: FriendRequestProcessor \u2192 FriendRequestResponder when  (emits xiigen.frien\u2026", async ({ page }) => {
    await page.goto("/friend-requests");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("10-friendrequestprocessor-friendrequestresp.png"), fullPage: true });
    await expect(page.getByTestId("friend-request-page")).toBeVisible();
  });

  test("P1-11: FriendRequestResponder \u2192 ConnectionGraphWriter when accepted (emits xiige\u2026", async ({ page }) => {
    await page.goto("/friend-requests");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("11-friendrequestresponder-connectiongraphwr.png"), fullPage: true });
    await expect(page.getByTestId("friend-request-page")).toBeVisible();
  });

  test("P1-12: ConnectionGraphWriter \u2192 FeedItemGenerator when  (emits xiigen.friend-requ\u2026", async ({ page }) => {
    await page.goto("/friend-requests");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("12-connectiongraphwriter-feeditemgenerator.png"), fullPage: true });
    await expect(page.getByTestId("friend-request-page")).toBeVisible();
  });

  test("P1-13: ConnectionGraphWriter \u2192 SocialNotificationDispatcher when  (emits xiigen.\u2026", async ({ page }) => {
    await page.goto("/friend-requests");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("13-connectiongraphwriter-socialnotification.png"), fullPage: true });
    await expect(page.getByTestId("friend-request-page")).toBeVisible();
  });

  test("P1-14: FeedItemGenerator \u2192 FeedScorer when  (emits xiigen.friend-request.feed-it\u2026", async ({ page }) => {
    await page.goto("/friend-requests");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("14-feeditemgenerator-feedscorer-when-emits.png"), fullPage: true });
    await expect(page.getByTestId("friend-request-page")).toBeVisible();
  });

  test("P1-15: FeedScorer \u2192 FeedDeliveryOrchestrator when  (emits xiigen.friend-request.\u2026", async ({ page }) => {
    await page.goto("/friend-requests");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("15-feedscorer-feeddeliveryorchestrator-when.png"), fullPage: true });
    await expect(page.getByTestId("friend-request-page")).toBeVisible();
  });

  test("P1-16: FeedDeliveryOrchestrator \u2192 SocialGraphAnalytics when  (emits xiigen.frien\u2026", async ({ page }) => {
    await page.goto("/friend-requests");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("16-feeddeliveryorchestrator-socialgraphanal.png"), fullPage: true });
    await expect(page.getByTestId("friend-request-page")).toBeVisible();
  });

  test("P1-17: SocialNotificationDispatcher \u2192 SocialGraphAnalytics when  (emits xiigen.f\u2026", async ({ page }) => {
    await page.goto("/friend-requests");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("17-socialnotificationdispatcher-socialgraph.png"), fullPage: true });
    await expect(page.getByTestId("friend-request-page")).toBeVisible();
  });

  test("P1-18: SocialGraphAnalytics \u2192 SocialConnectionsComplete when terminal (emits xii\u2026", async ({ page }) => {
    await page.goto("/friend-requests");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("18-socialgraphanalytics-socialconnectionsco.png"), fullPage: true });
    await expect(page.getByTestId("friend-request-page")).toBeVisible();
  });

});
// END P1 state coverage (P8)
