/**
 * FLOW-08 Marketplace — P1 state coverage (P8).
 *
 * Generated by scripts/gen-phase8-p1-coverage.py.
 * One test per NOT_TESTED / PARTIAL row in P3.
 * Mapping: docs/flow-coverage/marketplace/P5-ui-specs.md
 */

import { test, expect } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const SNAP = (name: string) =>
  path.join(__dirname, '..', '..', 'docs', 'e2e-snapshots', 'marketplace', name);

// P1 state coverage (P8) — auto-generated
test.describe('FLOW-08 marketplace — P1 state coverage', () => {

  test.beforeAll(async ({ request }) => {
    try {
      const r = await request.get('http://localhost:3000/health/live');
      if (!r.ok()) test.skip(true, 'Server not ready');
    } catch {
      test.skip(true, 'Server unreachable — start docker compose up');
    }
  });

  test("P1-01: ListingPublisher \u2014 submission_gateway step entered via POST /listings (au\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("01-listingpublisher-submission-gateway-step.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

  test("P1-02: ListingModerationEngine \u2014 moderation step entered via Called inline by T8\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("02-listingmoderationengine-moderation-step.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

  test("P1-03: ListingPriceValidator \u2014 guard step entered via Called inline by T83 (pric\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("03-listingpricevalidator-guard-step-entered.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

  test("P1-04: CatalogIndexer \u2014 data_pipeline step entered via ListingPublished event (u\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("04-catalogindexer-data-pipeline-step-entere.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

  test("P1-05: ListingFeedGenerator \u2014 data_pipeline step entered via ListingIndexed even\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("05-listingfeedgenerator-data-pipeline-step.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

  test("P1-06: ListingAnalyticsAggregator \u2014 analytics_engine step entered via TTL-window\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("06-listinganalyticsaggregator-analytics-eng.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

  test("P1-07: ListingSaveRequested \u2192 ListingPublisher when  (emits xiigen.marketplace.s\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("07-listingsaverequested-listingpublisher-wh.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

  test("P1-08: ListingPublisher \u2192 ListingModerationEngine when inline (emits xiigen.mark\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("08-listingpublisher-listingmoderationengine.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

  test("P1-09: ListingPublisher \u2192 ListingPriceValidator when inline (emits xiigen.market\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("09-listingpublisher-listingpricevalidator-w.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

  test("P1-10: ListingPublisher \u2192 CatalogIndexer when moderation passed (emits xiigen.ma\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("10-listingpublisher-catalogindexer-when-mod.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

  test("P1-11: ListingPublisher \u2192 ListingDraftSaved when moderation failed \u2192 DRAFT (emit\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("11-listingpublisher-listingdraftsaved-when.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

  test("P1-12: CatalogIndexer \u2192 ListingFeedGenerator when  (emits xiigen.marketplace.lis\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("12-catalogindexer-listingfeedgenerator-when.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

  test("P1-13: ListingFeedGenerator \u2192 ListingAnalyticsAggregator when  (emits xiigen.mar\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("13-listingfeedgenerator-listinganalyticsagg.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

  test("P1-14: ListingAnalyticsAggregator \u2192 MarketplaceFlowComplete when terminal (emits\u2026", async ({ page }) => {
    await page.goto("/marketplace/bootstrap-status");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("14-listinganalyticsaggregator-marketplacefl.png"), fullPage: true });
    await expect(page.getByTestId("bootstrap-status-page")).toBeVisible();
  });

});
// END P1 state coverage (P8)
