/**
 * FLOW-46 Platform Agent — P1 state coverage (P8).
 *
 * Generated by scripts/gen-phase8-p1-coverage.py.
 * One test per NOT_TESTED / PARTIAL row in P3.
 * Mapping: docs/flow-coverage/platform-agent/P5-ui-specs.md
 */

import { test, expect } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const SNAP = (name: string) =>
  path.join(__dirname, '..', '..', 'docs', 'e2e-snapshots', 'platform-agent', name);

// P1 state coverage (P8) — auto-generated
test.describe('FLOW-46 platform-agent — P1 state coverage', () => {

  test.beforeAll(async ({ request }) => {
    try {
      const r = await request.get('http://localhost:3000/health/live');
      if (!r.ok()) test.skip(true, 'Server not ready');
    } catch {
      test.skip(true, 'Server unreachable — start docker compose up');
    }
  });

  test("P1-03: PlatformContextEnricher \u2014 data_pipeline step entered via Inline \u2014 between\u2026", async ({ page }) => {
    await page.goto("/admin/platform-agent");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("01-platformcontextenricher-data-pipeline-st.png"), fullPage: true });
    await expect(page.getByTestId("page-platform-agent")).toBeVisible();
  });

  test("P1-06: PatternContributor \u2014 data_pipeline step entered via Super judge verdict +\u2026", async ({ page }) => {
    await page.goto("/admin/platform-agent");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("02-patterncontributor-data-pipeline-step-en.png"), fullPage: true });
    await expect(page.getByTestId("page-platform-agent")).toBeVisible();
  });

});
// END P1 state coverage (P8)
