/**
 * FLOW-06 User Groups Communities — P1 state coverage (P8).
 *
 * Generated by scripts/gen-phase8-p1-coverage.py.
 * One test per NOT_TESTED / PARTIAL row in P3.
 * Mapping: docs/flow-coverage/user-groups-communities/P5-ui-specs.md
 */

import { test, expect } from '@playwright/test';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const SNAP = (name: string) =>
  path.join(__dirname, '..', '..', 'docs', 'e2e-snapshots', 'user-groups-communities', name);
const SERVER_HEALTH_URL = process.env.SERVER_HEALTH_URL ?? 'http://localhost:3000/health/live';

// P1 state coverage (P8) — auto-generated
test.describe('FLOW-06 user-groups-communities — P1 state coverage', () => {

  test.beforeAll(async ({ request }) => {
    try {
      const r = await request.get(SERVER_HEALTH_URL);
      if (!r.ok()) test.skip(true, 'Server not ready');
    } catch {
      test.skip(true, 'Server unreachable — start docker compose up');
    }
  });

  test("P1-01: GroupMembershipProcessor \u2014 orchestration step entered via POST /groups/:i\u2026", async ({ page }) => {
    await page.goto("/groups/:groupId/admin/approvals");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("01-groupmembershipprocessor-orchestration-s.png"), fullPage: true });
    await expect(page.getByTestId("approval-queue")).toBeVisible();
  });

  test("P1-02: MembershipTierUpdater \u2014 data_pipeline step entered via MembershipAccepted\u2026", async ({ page }) => {
    await page.goto("/groups/:groupId/tier");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("02-membershiptierupdater-data-pipeline-step.png"), fullPage: true });
    await expect(page.getByTestId("tier-management")).toBeVisible();
  });

  test("P1-03: GroupFeedPopulator \u2014 ai_generation step entered via TierAssigned event (t\u2026", async ({ page }) => {
    await page.goto("/groups/:groupId/tier");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("03-groupfeedpopulator-ai-generation-step-en.png"), fullPage: true });
    await expect(page.getByTestId("tier-management")).toBeVisible();
  });

  test("P1-04: AccessControlEnforcer \u2014 validation step entered via Inline guard \u2014 called\u2026", async ({ page }) => {
    await page.goto("/groups/:groupId/admin/approvals");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("04-accesscontrolenforcer-validation-step-en.png"), fullPage: true });
    await expect(page.getByTestId("approval-queue")).toBeVisible();
  });

  test("P1-05: GroupJoinRequested \u2192 GroupMembershipProcessor when  (emits xiigen.user-gr\u2026", async ({ page }) => {
    await page.goto("/groups/:groupId/admin/approvals");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("05-groupjoinrequested-groupmembershipproces.png"), fullPage: true });
    await expect(page.getByTestId("approval-queue")).toBeVisible();
  });

  test("P1-06: GroupMembershipProcessor \u2192 AccessControlEnforcer when inline (emits xiige\u2026", async ({ page }) => {
    await page.goto("/groups/:groupId/admin/approvals");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("06-groupmembershipprocessor-accesscontrolen.png"), fullPage: true });
    await expect(page.getByTestId("approval-queue")).toBeVisible();
  });

  test("P1-07: GroupMembershipProcessor \u2192 MembershipTierUpdater when access granted (emi\u2026", async ({ page }) => {
    await page.goto("/groups/:groupId/membership");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("07-groupmembershipprocessor-membershiptieru.png"), fullPage: true });
    await expect(page.getByTestId("membership-active")).toBeVisible();
  });

  test("P1-08: GroupMembershipProcessor \u2192 MembershipRejected when access denied \u2014 termin\u2026", async ({ page }) => {
    await page.goto("/groups/:groupId/membership");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("08-groupmembershipprocessor-membershiprejec.png"), fullPage: true });
    await expect(page.getByTestId("membership-active")).toBeVisible();
  });

  test("P1-09: MembershipTierUpdater \u2192 GroupFeedPopulator when  (emits xiigen.user-group\u2026", async ({ page }) => {
    await page.goto("/groups/:groupId/tier");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("09-membershiptierupdater-groupfeedpopulator.png"), fullPage: true });
    await expect(page.getByTestId("tier-management")).toBeVisible();
  });

  test("P1-10: GroupFeedPopulator \u2192 AccessControlEnforcer when inline per item (emits xi\u2026", async ({ page }) => {
    await page.goto("/groups/:groupId/feed");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("10-groupfeedpopulator-accesscontrolenforcer.png"), fullPage: true });
    await expect(page.getByTestId("group-feed")).toBeVisible();
  });

  test("P1-11: GroupFeedPopulator \u2192 GroupFeedDelivered when terminal (emits xiigen.user-\u2026", async ({ page }) => {
    await page.goto("/groups/:groupId/feed");
    await page.waitForLoadState('networkidle');
    await page.screenshot({ path: SNAP("11-groupfeedpopulator-groupfeeddelivered-wh.png"), fullPage: true });
    await expect(page.getByTestId("group-feed")).toBeVisible();
  });

});
// END P1 state coverage (P8)
