/**
 * e2e-secrets-loader.ts
 *
 * Plain utility (NOT a NestJS service) that loads the session env file
 * generated by scripts/generate-session-env.sh into a typed E2eSecrets
 * object for consumption by E2E test suites.
 *
 * API keys are NEVER logged or asserted in tests — accessed only via
 * the typed object returned here and passed to provider constructors.
 *
 * Usage:
 *   const secrets = loadE2eSecrets();
 *   // secrets.anthropicApiKey may be '' — callers must check before use
 */

import * as fs from 'fs';
import * as path from 'path';

export interface E2eSecrets {
  sessionId: string;
  sessionShort: string;
  esIndexPrefix: string;
  redisKeyPrefix: string;
  pgSchema: string;
  qdrantCollectionPrefix: string;
  anthropicApiKey: string;
  geminiApiKey: string;
  pineconeApiKey: string;
  pineconeIndex: string;
  pineconeEnvironment: string;
  aiMaxOutputTokens: number;
  aiTestModelAnthropic: string;
  aiTestModelGemini: string;
}

/**
 * Candidate paths for the session env file:
 *   1. process.cwd()/.env.e2e-session   (standard: run `npm test` from server/)
 *   2. __dirname/../../../.env.e2e-session  (server/ root from src/testing/)
 *   3. __dirname/../../.env.e2e-session     (fallback)
 */
function findSessionEnvFile(): string {
  const candidates = [
    path.resolve(process.cwd(), '.env.e2e-session'),
    path.resolve(__dirname, '../../../.env.e2e-session'),
    path.resolve(__dirname, '../../.env.e2e-session'),
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) return p;
  }
  // Return the cwd-relative path even if absent (file won't be parsed)
  return candidates[0];
}

const SESSION_ENV_FILE = findSessionEnvFile();

/**
 * Parse a .env-style file into a plain Record<string, string>.
 * Lines starting with # and blank lines are skipped.
 * No shell variable expansion is performed.
 */
function parseEnvFile(filePath: string): Record<string, string> {
  if (!fs.existsSync(filePath)) {
    return {};
  }
  const lines = fs.readFileSync(filePath, 'utf8').split('\n');
  const result: Record<string, string> = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    if (key) result[key] = value;
  }
  return result;
}

/**
 * Resolve a config value: file wins over process.env over defaultValue.
 * This lets the suite be activated via either .env.e2e-session or environment
 * variables (useful in CI and when running from a different working directory).
 */
function resolve(fileEnv: Record<string, string>, key: string, defaultValue: string): string {
  return fileEnv[key] ?? process.env[key] ?? defaultValue;
}

/**
 * Load E2E session secrets from .env.e2e-session (searched in multiple paths)
 * or from process.env as fallback.
 * Returns sensible defaults for every field when neither source has a value
 * (pure mock-mode — no Docker, no cloud providers needed).
 */
export function loadE2eSecrets(): E2eSecrets {
  const env = parseEnvFile(SESSION_ENV_FILE);

  return {
    sessionId: resolve(env, 'SESSION_ID', 'mock-session'),
    sessionShort: resolve(env, 'SESSION_SHORT', 'mocksess'),
    esIndexPrefix: resolve(env, 'ES_INDEX_PREFIX', 'test-mocksess'),
    redisKeyPrefix: resolve(env, 'REDIS_KEY_PREFIX', 'test:mocksess:'),
    pgSchema: resolve(env, 'PG_SCHEMA', 'test_mocksess'),
    qdrantCollectionPrefix: resolve(env, 'QDRANT_COLLECTION_PREFIX', 'test_mocksess'),
    anthropicApiKey: resolve(env, 'BOOTSTRAP_ANTHROPIC_KEY', ''),
    geminiApiKey: resolve(env, 'BOOTSTRAP_GEMINI_KEY', ''),
    pineconeApiKey: resolve(env, 'BOOTSTRAP_PINECONE_KEY', ''),
    pineconeIndex: resolve(env, 'PINECONE_INDEX', ''),
    pineconeEnvironment: resolve(env, 'PINECONE_ENVIRONMENT', ''),
    aiMaxOutputTokens: parseInt(resolve(env, 'AI_MAX_OUTPUT_TOKENS', '200'), 10),
    aiTestModelAnthropic: resolve(env, 'AI_TEST_MODEL_ANTHROPIC', 'claude-haiku-4-5-20251001'),
    aiTestModelGemini: resolve(env, 'AI_TEST_MODEL_GEMINI', 'gemini-2.0-flash'),
  };
}

/**
 * Availability flags — computed from loaded secrets + environment.
 * Used by test suites to skip or activate provider-specific tests.
 */
export interface E2eAvailability {
  INMEMORY: true;
  ANTHROPIC: boolean;
  GEMINI: boolean;
  PINECONE: boolean;
  /** True when Ollama is reachable at OLLAMA_BASE_URL (default: http://localhost:11434). */
  OLLAMA: boolean;
  /** True when qwen2.5-coder:7b is pulled in the Ollama instance. */
  QWEN: boolean;
  /** True when LightRAG server is reachable at LIGHTRAG_BASE_URL (default: http://localhost:19100). */
  LIGHTRAG: boolean;
}

export function computeAvailability(secrets: E2eSecrets): E2eAvailability {
  // Synchronous ping via environment flags (set by run-e2e.sh or manually).
  // Runtime HTTP checks use pingHttp() in individual test suites.
  const ollamaAvail = process.env['OLLAMA_AVAILABLE'] === 'true';
  const qwenAvail = process.env['QWEN_AVAILABLE'] === 'true';
  const lightragAvail = process.env['LIGHTRAG_AVAILABLE'] === 'true';

  return {
    INMEMORY: true,
    ANTHROPIC: secrets.anthropicApiKey.length > 0,
    GEMINI: secrets.geminiApiKey.length > 0,
    PINECONE: secrets.pineconeApiKey.length > 0 && secrets.pineconeIndex.length > 0,
    OLLAMA: ollamaAvail,
    QWEN: qwenAvail,
    LIGHTRAG: lightragAvail,
  };
}
