/**
 * FLOW-25 BFA Rules (bfa-cross-flow-governance) — P11 edge-case rules (CF-985..CF-988).
 *
 * Source: docs/flow-coverage/bfa-cross-flow-governance/P10-server-specs.md
 * Generated by scripts/gen-p11-wave.py during Wave 3.
 */

import { MASTER_TENANT_ID } from '../bootstrap/bootstrap-seeder.service';

export const BFA_CROSS_FLOW_GOVERNANCE_BFA_RULES: Array<Record<string, unknown>> = [
  {
    ruleId: 'CF-985',
    flowId: 'FLOW-25',
    type: 'CONCURRENCY_CONSTRAINT',
    description:
      'EC-1 Optimistic concurrency on POST /api/dynamic/bfa-cross-flow-governance — winner 201, loser 409 {code:CONCURRENT_UPDATE}. Client retries (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-986',
    flowId: 'FLOW-25',
    type: 'IDEMPOTENCY_CONSTRAINT',
    description:
      'EC-2 X-Idempotency-Key replay — first call 201+stores; retries return 200 cached response; no duplicate side effects (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-987',
    flowId: 'FLOW-25',
    type: 'ORDERING_CONSTRAINT',
    description:
      'EC-4 Boundary validation — empty/null/zero primary field → 400 {code:VALIDATION_FAILED, details:[{field,reason}]}; no partial write (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-988',
    flowId: 'FLOW-25',
    type: 'DNA8_ORDERING',
    description:
      'EC-5 Fabric timeout — 504 {code:TIMEOUT, retryAfterMs}; outbox row retained; queue consumer retries deduplicatively (DNA-8) (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
];
