/**
 * FLOW-28 BFA Rules (blog-cms-modules) — P11 edge-case rules (CF-1003..CF-1006).
 *
 * Source: docs/flow-coverage/blog-cms-modules/P10-server-specs.md
 * Generated by scripts/gen-p11-wave.py during Wave 3.
 */

import { MASTER_TENANT_ID } from '../bootstrap/bootstrap-seeder.service';

export const BLOG_CMS_MODULES_BFA_RULES: Array<Record<string, unknown>> = [
  {
    ruleId: 'CF-1003',
    flowId: 'FLOW-28',
    type: 'CONCURRENCY_CONSTRAINT',
    description:
      'EC-4 Optimistic concurrency on POST /api/dynamic/blog-cms-modules — winner 201, loser 409 {code:CONCURRENT_UPDATE}. Client retries (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-1004',
    flowId: 'FLOW-28',
    type: 'IDEMPOTENCY_CONSTRAINT',
    description:
      'EC-5 X-Idempotency-Key replay — first call 201+stores; retries return 200 cached response; no duplicate side effects (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-1005',
    flowId: 'FLOW-28',
    type: 'ORDERING_CONSTRAINT',
    description:
      'EC-7 Boundary validation — empty/null/zero primary field → 400 {code:VALIDATION_FAILED, details:[{field,reason}]}; no partial write (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-1006',
    flowId: 'FLOW-28',
    type: 'DNA8_ORDERING',
    description:
      'EC-8 Fabric timeout — 504 {code:TIMEOUT, retryAfterMs}; outbox row retained; queue consumer retries deduplicatively (DNA-8) (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
];
