/**
 * FLOW-40 BFA Rules (client-push) — P11 edge-case rules (CF-1062..CF-1065).
 *
 * Source: docs/flow-coverage/client-push/P10-server-specs.md
 * Generated by scripts/gen-p11-wave.py during Wave 3.
 */

import { MASTER_TENANT_ID } from '../bootstrap/bootstrap-seeder.service';

export const CLIENT_PUSH_BFA_RULES: Array<Record<string, unknown>> = [
  {
    ruleId: 'CF-1062',
    flowId: 'FLOW-40',
    type: 'CONCURRENCY_CONSTRAINT',
    description:
      'EC-3 Optimistic concurrency on POST /api/dynamic/client-push — winner 201, loser 409 {code:CONCURRENT_UPDATE}. Client retries (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-1063',
    flowId: 'FLOW-40',
    type: 'IDEMPOTENCY_CONSTRAINT',
    description:
      'EC-4 X-Idempotency-Key replay — first call 201+stores; retries return 200 cached response; no duplicate side effects (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-1064',
    flowId: 'FLOW-40',
    type: 'ORDERING_CONSTRAINT',
    description:
      'EC-6 Boundary validation — empty/null/zero primary field → 400 {code:VALIDATION_FAILED, details:[{field,reason}]}; no partial write (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-1065',
    flowId: 'FLOW-40',
    type: 'DNA8_ORDERING',
    description:
      'EC-7 Fabric timeout — 504 {code:TIMEOUT, retryAfterMs}; outbox row retained; queue consumer retries deduplicatively (DNA-8) (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
];
