/**
 * FLOW-27 BFA Rules (human-interaction-gate) — P11 edge-case rules (CF-996..CF-1002).
 *
 * Source: docs/flow-coverage/human-interaction-gate/P10-server-specs.md
 * Generated by scripts/gen-p11-wave.py during Wave 3.
 */

import { MASTER_TENANT_ID } from '../bootstrap/bootstrap-seeder.service';

export const HUMAN_INTERACTION_GATE_BFA_RULES: Array<Record<string, unknown>> = [
  {
    ruleId: 'CF-996',
    flowId: 'FLOW-27',
    type: 'CONCURRENCY_CONSTRAINT',
    description:
      'EC-1 Optimistic concurrency on POST /api/dynamic/human-interaction-gate — winner 201, loser 409 {code:CONCURRENT_UPDATE}. Client retries (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-997',
    flowId: 'FLOW-27',
    type: 'IDEMPOTENCY_CONSTRAINT',
    description:
      'EC-2 X-Idempotency-Key replay — first call 201+stores; retries return 200 cached response; no duplicate side effects (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-998',
    flowId: 'FLOW-27',
    type: 'ORDERING_CONSTRAINT',
    description:
      'EC-4 Boundary validation — empty/null/zero primary field → 400 {code:VALIDATION_FAILED, details:[{field,reason}]}; no partial write (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-999',
    flowId: 'FLOW-27',
    type: 'DNA8_ORDERING',
    description:
      'EC-5 Fabric timeout — 504 {code:TIMEOUT, retryAfterMs}; outbox row retained; queue consumer retries deduplicatively (DNA-8) (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-1000',
    flowId: 'FLOW-27',
    type: 'CONCURRENCY_CONSTRAINT',
    description:
      'EC-6 Optimistic concurrency on POST /api/dynamic/human-interaction-gate — winner 201, loser 409 {code:CONCURRENT_UPDATE}. Client retries (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-1001',
    flowId: 'FLOW-27',
    type: 'IDEMPOTENCY_CONSTRAINT',
    description:
      'EC-7 X-Idempotency-Key replay — first call 201+stores; retries return 200 cached response; no duplicate side effects (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-1002',
    flowId: 'FLOW-27',
    type: 'ORDERING_CONSTRAINT',
    description:
      'EC-9 Boundary validation — empty/null/zero primary field → 400 {code:VALIDATION_FAILED, details:[{field,reason}]}; no partial write (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
];
