/**
 * FLOW-32 BFA Rules (sharable-flows-marketplace) — P11 edge-case rules (CF-1019..CF-1022).
 *
 * Source: docs/flow-coverage/sharable-flows-marketplace/P10-server-specs.md
 * Generated by scripts/gen-p11-wave.py during Wave 3.
 */

import { MASTER_TENANT_ID } from '../bootstrap/bootstrap-seeder.service';

export const SHARABLE_FLOWS_MARKETPLACE_BFA_RULES: Array<Record<string, unknown>> = [
  {
    ruleId: 'CF-1019',
    flowId: 'FLOW-32',
    type: 'CONCURRENCY_CONSTRAINT',
    description:
      'EC-1 Optimistic concurrency on POST /api/dynamic/sharable-flows-marketplace — winner 201, loser 409 {code:CONCURRENT_UPDATE}. Client retries (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-1020',
    flowId: 'FLOW-32',
    type: 'IDEMPOTENCY_CONSTRAINT',
    description:
      'EC-2 X-Idempotency-Key replay — first call 201+stores; retries return 200 cached response; no duplicate side effects (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-1021',
    flowId: 'FLOW-32',
    type: 'ORDERING_CONSTRAINT',
    description:
      'EC-4 Boundary validation — empty/null/zero primary field → 400 {code:VALIDATION_FAILED, details:[{field,reason}]}; no partial write (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
  {
    ruleId: 'CF-1022',
    flowId: 'FLOW-32',
    type: 'DNA8_ORDERING',
    description:
      'EC-5 Fabric timeout — 504 {code:TIMEOUT, retryAfterMs}; outbox row retained; queue consumer retries deduplicatively (DNA-8) (P11).',
    violationSeverity: 'BUILD_FAILURE',
    connectionType: 'FLOW_SCOPED',
    knowledgeScope: 'GLOBAL',
    tenantId: MASTER_TENANT_ID,
  },
];
