#!/usr/bin/env python3
"""
P11 Wave N BFA rule registration — scripted injector.

For each flow supplied on the command line:
  1. Parse P10-server-specs.md → extract (ec_num, cf_num, rule_type) tuples.
  2. Read {slug}-bfa-rules.ts, locate the SCOPE_ISOLATION entry.
  3. Inject new rule entries immediately before that entry (preserving
     the FC-32 convention that scope_isolation is always the last rule).
  4. Generate __tests__/{slug}-bfa-rules.spec.ts registration tests.

Idempotent: if a CF is already registered in the file, the script skips
that flow entirely.

Usage:
  python scripts/gen-p11-wave.py user-groups-communities:6 completion-gamification:5 ...
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "server" / "src" / "engine-contracts"
TESTS_DIR = CONTRACTS / "__tests__"
FLOW_COVERAGE = ROOT / "docs" / "flow-coverage"


def classify(ec_text: str) -> str:
    t = ec_text.lower()
    if "concurrent" in t:
        return "CONCURRENCY_CONSTRAINT"
    if "retried" in t or "idempot" in t:
        return "IDEMPOTENCY_CONSTRAINT"
    if "boundary" in t or "empty" in t or "null" in t:
        return "ORDERING_CONSTRAINT"
    if "timeout" in t or "partial failure" in t:
        return "DNA8_ORDERING"
    return "ORDERING_CONSTRAINT"


def describe(ec: int, rtype: str, slug: str) -> str:
    if rtype == "CONCURRENCY_CONSTRAINT":
        return (
            f"EC-{ec} Optimistic concurrency on POST /api/dynamic/{slug} — "
            f"winner 201, loser 409 {{code:CONCURRENT_UPDATE}}. Client retries (P11)."
        )
    if rtype == "IDEMPOTENCY_CONSTRAINT":
        return (
            f"EC-{ec} X-Idempotency-Key replay — first call 201+stores; "
            f"retries return 200 cached response; no duplicate side effects (P11)."
        )
    if rtype == "ORDERING_CONSTRAINT":
        return (
            f"EC-{ec} Boundary validation — empty/null/zero primary field → "
            f"400 {{code:VALIDATION_FAILED, details:[{{field,reason}}]}}; "
            f"no partial write (P11)."
        )
    if rtype == "DNA8_ORDERING":
        return (
            f"EC-{ec} Fabric timeout — 504 {{code:TIMEOUT, retryAfterMs}}; "
            f"outbox row retained; queue consumer retries deduplicatively (DNA-8) (P11)."
        )
    return f"EC-{ec} enforcement (P11)."


def parse_p10(slug: str):
    p = FLOW_COVERAGE / slug / "P10-server-specs.md"
    if not p.exists():
        return []
    text = p.read_text(encoding="utf-8")
    pattern = re.compile(
        r"## EC-(\d+): (.+?)\n[^#]*?BFA rule:\*\*\s*`CF-(\d+)`",
        re.DOTALL,
    )
    out = []
    for m in pattern.finditer(text):
        ec_num = int(m.group(1))
        ec_text = m.group(2).strip()
        cf_num = int(m.group(3))
        out.append({
            "ec": ec_num,
            "cf": cf_num,
            "type": classify(ec_text),
            "ec_text": ec_text,
        })
    return out


def rule_block(
    flow_id: str,
    ec: int,
    cf: int,
    rtype: str,
    desc: str,
    include_tenant_id: bool,
) -> str:
    tail = (
        "    violationSeverity: 'BUILD_FAILURE',\n"
        "    connectionType: 'FLOW_SCOPED',\n"
        "    knowledgeScope: 'GLOBAL',\n"
    )
    if include_tenant_id:
        tail += "    tenantId: MASTER_TENANT_ID,\n"
    return (
        "  {\n"
        f"    ruleId: 'CF-{cf}',\n"
        f"    flowId: '{flow_id}',\n"
        f"    type: '{rtype}',\n"
        f"    description:\n"
        f"      '{desc}',\n"
        + tail
        + "  },\n"
    )


def slug_to_const(slug: str) -> str:
    return slug.replace("-", "_").upper() + "_BFA_RULES"


def create_new_file(slug: str, flow_num: int, ecs: list) -> str:
    """Generate a fresh {slug}-bfa-rules.ts containing only P11 rules.

    New files omit scope_isolation — FC-32 arbiter registration is a separate
    concern from P11 edge-case rule registration.
    """
    const_name = slug_to_const(slug)
    flow_id = f"FLOW-{flow_num:02d}"
    cf_first = ecs[0]["cf"]
    cf_last = ecs[-1]["cf"]

    lines = [
        f"/**",
        f" * {flow_id} BFA Rules ({slug}) — P11 edge-case rules (CF-{cf_first}..CF-{cf_last}).",
        f" *",
        f" * Source: docs/flow-coverage/{slug}/P10-server-specs.md",
        f" * Generated by scripts/gen-p11-wave.py during Wave 3.",
        f" */",
        f"",
        f"import {{ MASTER_TENANT_ID }} from '../bootstrap/bootstrap-seeder.service';",
        f"",
        f"export const {const_name}: Array<Record<string, unknown>> = [",
    ]
    body = []
    for ec in ecs:
        desc = describe(ec["ec"], ec["type"], slug)
        body.append(rule_block(flow_id, ec["ec"], ec["cf"], ec["type"], desc, True))
    return "\n".join(lines) + "\n" + "".join(body) + "];\n"


def inject(slug: str, flow_num: int):
    fp = CONTRACTS / f"{slug}-bfa-rules.ts"
    ecs = parse_p10(slug)
    if not ecs:
        print(f"  SKIP {slug}: no P10 specs parsed")
        return None, None

    if not fp.exists():
        content = create_new_file(slug, flow_num, ecs)
        fp.write_text(content, encoding="utf-8", newline="\n")
        print(f"  OK {slug}: created new {fp.name} with {len(ecs)} P11 rules")
        return content, ecs

    text = fp.read_text(encoding="utf-8")

    for ec in ecs:
        if f"ruleId: 'CF-{ec['cf']}'" in text:
            print(f"  SKIP {slug}: CF-{ec['cf']} already registered (idempotent)")
            return text, ecs

    # Detect file format: rich (has MASTER_TENANT_ID *import*) vs simple.
    # Substring match would false-positive on mentions inside description
    # strings (e.g. platform-agent references the identifier in prose).
    has_mti_import = bool(
        re.search(r"^\s*import\s*\{[^}]*\bMASTER_TENANT_ID\b", text, re.MULTILINE)
    )

    flow_id = f"FLOW-{flow_num:02d}"
    cf_first = ecs[0]["cf"]
    cf_last = ecs[-1]["cf"]

    blocks = [
        f"  // P11 (CF-{cf_first}..CF-{cf_last}) — edge-case coverage from "
        f"docs/flow-coverage/{slug}/P10-server-specs.md\n"
    ]
    for ec in ecs:
        desc = describe(ec["ec"], ec["type"], slug)
        blocks.append(
            rule_block(flow_id, ec["ec"], ec["cf"], ec["type"], desc, has_mti_import)
        )
    injection = "".join(blocks)

    # First try strict anchor (files that explicitly mark SCOPE_ISOLATION)
    m = re.search(
        r"\n  \{\s*\n\s*ruleId: '[^']+',\s*\n\s*flowId: '[^']+',\s*\n\s*type: 'SCOPE_ISOLATION'",
        text,
    )
    if m:
        insert_pos = m.start() + 1  # line-start of `  {`
    else:
        # Fallback: find last rule block before the array closing `\n];`.
        closing = re.search(r"\n\];\s*\n?\s*$", text)
        if not closing:
            print(f"  SKIP {slug}: no array-closing `];` found")
            return None, None
        # walk back to the last `  {` that begins the final rule block
        segment = text[: closing.start()]
        # Find last occurrence of a line starting with `  {`
        last_brace = None
        for m2 in re.finditer(r"(?m)^  \{", segment):
            last_brace = m2
        if last_brace is None:
            print(f"  SKIP {slug}: no rule-block anchor found (empty array?)")
            return None, None
        insert_pos = last_brace.start()

    # Absorb any `  // ...` comment lines immediately preceding the anchor.
    while True:
        before = text[:insert_pos].rstrip("\n")
        last_nl = before.rfind("\n")
        prev_line = before[last_nl + 1:] if last_nl != -1 else before
        if prev_line.startswith("  //"):
            insert_pos = insert_pos - len(prev_line) - 1
        else:
            break

    new_text = text[:insert_pos] + injection + text[insert_pos:]
    fp.write_text(new_text, encoding="utf-8", newline="\n")
    print(f"  OK {slug}: inserted {len(ecs)} rules before SCOPE_ISOLATION")
    return new_text, ecs


def find_export_name(text: str) -> str | None:
    # Matches both typed (`export const X: Array<...> = [`)
    # and untyped (`export const X = [`) exports.
    m = re.search(r"export const (\w+)(?:\s*:\s*Array[^=]*)?\s*=\s*\[", text)
    return m.group(1) if m else None


def find_scope_isolation_rule_id(text: str) -> str | None:
    m = re.search(
        r"ruleId: '([^']+)',\s*\n\s*flowId: '[^']+',\s*\n\s*type: 'SCOPE_ISOLATION'",
        text,
    )
    if m:
        return m.group(1)
    # Fallback: simple-style files (no `type` field). The scope_isolation rule
    # is always the LAST entry in the array by FC-32 convention.
    closing = re.search(r"\n\];\s*\n?\s*$", text)
    if not closing:
        return None
    segment = text[: closing.start()]
    # Find all ruleId declarations — return the last one, which is scope_isolation.
    rules = re.findall(r"ruleId: '([^']+)'", segment)
    return rules[-1] if rules else None


def type_name_for_header(rtype: str) -> str:
    return {
        "CONCURRENCY_CONSTRAINT": "concurrency",
        "IDEMPOTENCY_CONSTRAINT": "idempotency",
        "ORDERING_CONSTRAINT": "boundary validation",
        "DNA8_ORDERING": "fabric timeout / DNA-8 outbox",
    }.get(rtype, rtype.lower())


def file_has_real_scope_isolation(rules_text: str) -> bool:
    """Return True iff the rules array contains an entry tagged as
    scope_isolation — either via explicit `type: 'SCOPE_ISOLATION'`
    or via a comment marking the final CF-NN-K entry as scope_isolation.
    New Wave 3 files are P11-only and contain neither.
    """
    if "SCOPE_ISOLATION" in rules_text:
        return True
    if re.search(r"scope_isolation arbiter", rules_text):
        return True
    return False


def write_tests(slug: str, flow_num: int, rules_text: str, ecs: list):
    if rules_text is None or not ecs:
        return
    export_name = find_export_name(rules_text)
    if not export_name:
        print(f"  SKIP test {slug}: missing export name")
        return
    has_real_scope = file_has_real_scope_isolation(rules_text)
    scope_iso_id = find_scope_isolation_rule_id(rules_text) if has_real_scope else None

    TESTS_DIR.mkdir(parents=True, exist_ok=True)
    tp = TESTS_DIR / f"{slug}-bfa-rules.spec.ts"
    if tp.exists():
        print(f"  SKIP test {slug}: {tp.name} already exists")
        return

    flow_id = f"FLOW-{flow_num:02d}"
    cf_first = ecs[0]["cf"]
    cf_last = ecs[-1]["cf"]

    lines = [
        "/**",
        f" * {flow_id} BFA rules — P11 additions.",
        " * Registration-only gate: each CF-NNN from P10 appears in the rules array.",
        " */",
        f"import {{ {export_name} }} from '../{slug}-bfa-rules';",
        "",
        f"describe('{flow_id} BFA rules — P11 additions (CF-{cf_first}..CF-{cf_last})', () => {{",
        f"  const findRule = (id: string) =>",
        f"    {export_name}.find((r) => r.ruleId === id);",
        "",
    ]
    for ec in ecs:
        cf = ec["cf"]
        rtype = ec["type"]
        label = type_name_for_header(rtype)
        lines.append(f"  it('CF-{cf} ({label}) is registered', () => {{")
        lines.append(f"    const r = findRule('CF-{cf}');")
        lines.append(f"    expect(r).toBeDefined();")
        lines.append(f"    expect(r?.type).toBe('{rtype}');")
        lines.append(f"    expect(r?.flowId).toBe('{flow_id}');")
        lines.append("  });")
        lines.append("")
    # Scope_isolation tail assertion — only meaningful for files that
    # actually contain a scope_isolation rule. New Wave 3 files are P11-only.
    if has_real_scope and scope_iso_id:
        has_scope_type = re.search(
            r"ruleId: '"
            + re.escape(scope_iso_id)
            + r"',\s*\n\s*flowId: '[^']+',\s*\n\s*type: 'SCOPE_ISOLATION'",
            rules_text,
        )
        lines.append(
            f"  it('scope_isolation ({scope_iso_id}) remains the last rule after P11 additions', () => {{"
        )
        lines.append(f"    const last = {export_name}[{export_name}.length - 1];")
        lines.append(f"    expect(last?.ruleId).toBe('{scope_iso_id}');")
        if has_scope_type:
            lines.append("    expect(last?.type).toBe('SCOPE_ISOLATION');")
        lines.append("  });")
    else:
        # Count registered P11 rules (our CF range only) — this works for
        # both fresh files (where size == total rules) and injection files
        # (where legacy rules exist alongside our P11 additions).
        cf_ids = sorted({ec["cf"] for ec in ecs})
        ids_ts = ", ".join(f"'CF-{cf}'" for cf in cf_ids)
        lines.append(
            f"  it('all {len(ecs)} P11 rules registered — no omissions', () => {{"
        )
        lines.append(f"    const expected = [{ids_ts}];")
        lines.append(
            f"    const registered = expected.filter((id) => findRule(id) !== undefined);"
        )
        lines.append(f"    expect(registered.length).toBe({len(ecs)});")
        lines.append("  });")
    lines.append("});")
    lines.append("")

    tp.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"  OK {slug}: wrote {tp.name} ({len(ecs) + 1} tests)")


def main():
    if len(sys.argv) < 2:
        print("usage: gen-p11-wave.py <slug>:<flow_num> [<slug>:<flow_num> ...]")
        return 1
    total = 0
    for arg in sys.argv[1:]:
        slug, num = arg.split(":")
        n = int(num)
        print(f"[FLOW-{n:02d}] {slug}")
        new_text, ecs = inject(slug, n)
        if new_text and ecs:
            write_tests(slug, n, new_text, ecs)
            total += len(ecs)
    print(f"\nTotal rules inserted: {total}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
