#!/usr/bin/env python3
"""
Phase 8 of FLOW-UI-COVERAGE-PLAN-v2 — Playwright mock-state spec authoring.

For each stub-pattern page (has `data-testid="page-{slug}"` + mock-key `${k}` map block),
emit `client/e2e/{slug}-mock-states.spec.ts` covering:
  - default route (no mock param): asserts page-{slug} + {slug}-default testids, screenshot
  - per-state route (?mock=<key>): asserts {slug}-state-N testid, screenshot

PNGs land at `docs/e2e-snapshots/{slug}/` so P4 regenerator flips to PNG_EXISTS after
P13 runs them.

Usage:
  python scripts/gen-phase8-mock-specs.py --flows FLOW-13 FLOW-14 ...
  python scripts/gen-phase8-mock-specs.py --all
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SESSIONS = ROOT / "docs" / "sessions"
CLIENT_PAGES = ROOT / "client" / "src" / "pages"
CLIENT_E2E = ROOT / "client" / "e2e"
APP_TSX = ROOT / "client" / "src" / "App.tsx"

MOCK_MAP_RE = re.compile(r"\[((?:'[^']+',?\s*)+)\]\.map")
ROUTE_RE = re.compile(r'<Route\s+path="([^"]+)"\s+element=\{<(\w+)\s*/>\}')


def load_automation(flow_id: str) -> dict:
    return json.load(open(SESSIONS / flow_id / "flow-ui-automation.json", encoding="utf-8"))


def read_page_stub(slug: str) -> tuple[str, list[str]] | None:
    d = CLIENT_PAGES / slug
    if not d.exists():
        return None
    for tsx in d.glob("*.tsx"):
        text = tsx.read_text(encoding="utf-8", errors="ignore")
        if f'data-testid="page-{slug}"' not in text:
            continue
        m = MOCK_MAP_RE.search(text)
        if not m:
            continue
        keys_blob = m.group(1)
        keys = [k.strip().strip("'") for k in keys_blob.split(",") if k.strip()]
        return tsx.stem, keys
    return None


def read_app_routes() -> dict[str, str]:
    """Return {ComponentName: routePath} from App.tsx."""
    text = APP_TSX.read_text(encoding="utf-8", errors="ignore")
    result = {}
    for m in ROUTE_RE.finditer(text):
        path, comp = m.group(1), m.group(2)
        result[comp] = path
    return result


def render_spec(flow_id: str, slug: str, route: str, comp_stem: str, mock_keys: list[str]) -> str:
    display = slug.replace("-", " ").title()
    header = f"""/**
 * {flow_id} — {display} Mock-State Coverage (auto-generated by gen-phase8-mock-specs.py)
 *
 * Covers every Phase-1 business state via ?mock=<key> query param against the stub page.
 * PNGs land at docs/e2e-snapshots/{slug}/ to satisfy FLOW-UI-COVERAGE-PLAN-v2 P4 gate.
 *
 * Mock keys ({len(mock_keys)}): {", ".join(f"'{k}'" for k in mock_keys)}
 */

import {{ test, expect }} from '@playwright/test';
import * as path from 'path';
import {{ fileURLToPath }} from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const SNAP = (name: string) =>
  path.join(__dirname, '..', '..', 'docs', 'e2e-snapshots', '{slug}', name);

test.describe('{flow_id} — {display} mock states', () => {{

  test('default: page-{slug} renders with state index', async ({{ page }}) => {{
    await page.goto('{route}');
    await page.waitForLoadState('networkidle');
    await expect(page.getByTestId('page-{slug}')).toBeVisible();
    await expect(page.getByTestId('{slug}-default')).toBeVisible();
    await page.screenshot({{ path: SNAP('default.png'), fullPage: true }});
  }});
"""
    body = []
    for i, mk in enumerate(mock_keys, 1):
        body.append(f"""
  test('state-{i} ({mk}): {slug}-state-{i} visible', async ({{ page }}) => {{
    await page.goto('{route}?mock={mk}');
    await page.waitForLoadState('networkidle');
    await expect(page.getByTestId('{slug}-state-{i}')).toBeVisible();
    await page.screenshot({{ path: SNAP('state-{i}-{mk}.png'), fullPage: true }});
  }});""")
    footer = "\n});\n"
    return header + "".join(body) + footer


def process_flow(flow_id: str, routes_map: dict[str, str]) -> dict:
    auto = load_automation(flow_id)
    slug = auto["slug"]
    stub = read_page_stub(slug)
    if stub is None:
        return {"flowId": flow_id, "slug": slug, "skipped": "no-stub-pattern"}
    comp_stem, mock_keys = stub
    # Resolve route from App.tsx
    route = routes_map.get(comp_stem)
    if not route:
        return {"flowId": flow_id, "slug": slug, "skipped": f"no-route-for-{comp_stem}"}
    # Ensure snapshot dir
    snap_dir = ROOT / "docs" / "e2e-snapshots" / slug
    snap_dir.mkdir(parents=True, exist_ok=True)
    # Write spec
    spec_path = CLIENT_E2E / f"{slug}-mock-states.spec.ts"
    spec_path.write_text(render_spec(flow_id, slug, route, comp_stem, mock_keys), encoding="utf-8")
    return {"flowId": flow_id, "slug": slug, "route": route, "keys": len(mock_keys),
            "spec": str(spec_path.relative_to(ROOT))}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--flows", nargs="*", help="Flow IDs, e.g. FLOW-13 FLOW-14")
    ap.add_argument("--all", action="store_true")
    args = ap.parse_args()

    routes_map = read_app_routes()
    if args.all:
        fids = [f"FLOW-{n:02d}" for n in range(48)]
    else:
        fids = args.flows or []
    if not fids:
        ap.error("Provide --flows ... or --all")

    results = []
    for fid in fids:
        try:
            r = process_flow(fid, routes_map)
        except FileNotFoundError:
            r = {"flowId": fid, "skipped": "no-automation-json"}
        results.append(r)
        if "skipped" in r:
            print(f"  {fid}: skip ({r['skipped']})")
        else:
            print(f"  {fid}: wrote {r['spec']}  ({r['keys']} states @ {r['route']})")

    authored = [r for r in results if "skipped" not in r]
    print(f"\n{len(authored)}/{len(results)} flows: spec authored")
    return 0


if __name__ == "__main__":
    sys.exit(main())
