/**
 * FLOW-00.3 E2E — AfPipeline execution chain (post DEV-23 S3 refactor)
 *
 * After the S3 refactor, cost propagation through AiDispatcher → CostTracker
 * → AfPipeline has been decoupled. AfPipeline no longer receives a cost tracker
 * or AI provider directly. All execution is delegated to GenericNodeExecutor.
 *
 * These tests verify the end-to-end contract of the new pipeline architecture:
 *   E2E-1: Pipeline executes and returns DataProcessResult (DNA-3)
 *   E2E-2: PipelineResult has all required structural fields
 *   E2E-3: passed flag reflects executor status
 *   E2E-4: stages[] contains one entry per trace node
 *   E2E-5: errors[] collects FAIL node errorCodes from trace
 *   E2E-6: Pipeline with FAIL executor returns DataProcessResult.failure
 *   E2E-7: Multiple sequential runs each produce independent results
 */

import { DataProcessResult } from '../../src/kernel/data-process-result';
import { GenericNodeExecutor } from '../../src/engine/generic-node-executor';
import { StationInput } from '../../src/af-stations/base';
import { AfPipeline } from '../../src/af-stations/af-pipeline';

// ── Setup ────────────────────────────────────────────────────────────────────

const TENANT_ID = 'flow003-e2e-tenant';

function makeInput(taskType = 'T-E2E-CHAIN'): StationInput {
  return new StationInput({
    tenantId: TENANT_ID,
    taskType,
    spec: { name: 'ChainTestService', purpose: 'e2e chain verification' },
  });
}

function makePassExecutor(
  trace: Array<{
    nodeId: string;
    status?: 'PASS' | 'FAIL' | 'SKIP';
    durationMs?: number;
    errorCode?: string;
  }> = [],
): GenericNodeExecutor {
  const fullTrace = trace.map((n) => ({
    nodeId: n.nodeId,
    nodeType: n.nodeId,
    status: n.status ?? 'PASS',
    durationMs: n.durationMs ?? 10,
    errorCode: n.errorCode,
  }));
  return {
    execute: jest.fn(async () =>
      DataProcessResult.success({
        runId: `run-e2e-${Date.now()}`,
        status: 'PASS',
        score: 85,
        trace: fullTrace,
        finalOutput: { code: '// generated by e2e test' },
        promoted: true,
        promotionLevel: 'MINIMAL',
      }),
    ),
    getTrace: jest.fn(async () => DataProcessResult.success(null)),
  } as unknown as GenericNodeExecutor;
}

function makeFailExecutor(
  errorCode = 'EXEC_FAIL',
  errorMessage = 'executor failed',
): GenericNodeExecutor {
  return {
    execute: jest.fn(async () => DataProcessResult.failure(errorCode, errorMessage)),
    getTrace: jest.fn(async () => DataProcessResult.success(null)),
  } as unknown as GenericNodeExecutor;
}

// ── E2E Tests ────────────────────────────────────────────────────────────────

describe('AfPipeline — Execution Chain E2E [E2E]', () => {
  describe('E2E-1: Pipeline returns DataProcessResult (DNA-3)', () => {
    it('result is a DataProcessResult instance', async () => {
      const pipeline = new AfPipeline(makePassExecutor());
      const result = await pipeline.execute(makeInput());
      expect(result).toBeInstanceOf(DataProcessResult);
      expect(result.isSuccess).toBe(true);
    });
  });

  describe('E2E-2: PipelineResult has all required structural fields', () => {
    it('result.data contains passed, artifactId, stages, costs, enrichedInput, errors, warnings', async () => {
      const pipeline = new AfPipeline(makePassExecutor());
      const result = await pipeline.execute(makeInput());

      expect(result.isSuccess).toBe(true);
      const pr = result.data!;

      expect(typeof pr.passed).toBe('boolean');
      expect(typeof pr.artifactId).toBe('string');
      expect(typeof pr.promotionLevel).toBe('string');
      expect(Array.isArray(pr.stages)).toBe(true);
      expect(typeof pr.totalElapsedMs).toBe('number');
      expect(typeof pr.total_cost_usd).toBe('number');
      expect(typeof pr.cost_by_model).toBe('object');
      expect(pr.enrichedInput).toBeDefined();
      expect(Array.isArray(pr.errors)).toBe(true);
      expect(Array.isArray(pr.warnings)).toBe(true);
    });
  });

  describe('E2E-3: passed flag reflects executor status', () => {
    it('passed=true when executor returns PASS', async () => {
      const pipeline = new AfPipeline(makePassExecutor());
      const result = await pipeline.execute(makeInput());

      expect(result.isSuccess).toBe(true);
      expect(result.data!.passed).toBe(true);
    });
  });

  describe('E2E-4: stages[] contains one entry per trace node', () => {
    it('stages count equals trace node count from executor', async () => {
      const trace = [
        { nodeId: 'rag-retrieve', durationMs: 15 },
        { nodeId: 'decompose', durationMs: 8 },
        { nodeId: 'ai-generate', durationMs: 340 },
        { nodeId: 'validate', durationMs: 12 },
        { nodeId: 'score', durationMs: 5 },
        { nodeId: 'feedback', durationMs: 20 },
      ];
      const pipeline = new AfPipeline(makePassExecutor(trace));
      const result = await pipeline.execute(makeInput());

      expect(result.isSuccess).toBe(true);
      const stages = result.data!.stages;
      expect(stages).toHaveLength(6);
      const nodeIds = stages.map((s) => s.stage);
      expect(nodeIds).toContain('rag-retrieve');
      expect(nodeIds).toContain('ai-generate');
      expect(nodeIds).toContain('feedback');
    });
  });

  describe('E2E-5: errors[] collects FAIL node errorCodes from trace', () => {
    it('errors list contains errorCode for each FAIL node in trace', async () => {
      const trace = [
        { nodeId: 'rag-retrieve', status: 'PASS' as const },
        { nodeId: 'ai-generate', status: 'FAIL' as const, errorCode: 'AI_TIMEOUT' },
        { nodeId: 'validate', status: 'FAIL' as const, errorCode: 'VALIDATION_FAIL' },
      ];
      const pipeline = new AfPipeline(makePassExecutor(trace));
      const result = await pipeline.execute(makeInput());

      expect(result.isSuccess).toBe(true);
      const pr = result.data!;
      expect(pr.errors).toContain('AI_TIMEOUT');
      expect(pr.errors).toContain('VALIDATION_FAIL');
    });
  });

  describe('E2E-6: executor failure → DataProcessResult.failure returned', () => {
    it('pipeline.execute returns failure when executor fails', async () => {
      const pipeline = new AfPipeline(
        makeFailExecutor('NODE_REGISTRY_DOWN', 'registry unavailable'),
      );
      const result = await pipeline.execute(makeInput());

      expect(result.isSuccess).toBe(false);
      expect(result.data).toBeFalsy();
      expect(result.errorCode).toBe('NODE_REGISTRY_DOWN');
      expect(result.errorMessage).toBe('registry unavailable');
    });
  });

  describe('E2E-7: sequential runs produce independent results', () => {
    it('two runs return different artifactIds', async () => {
      const pipeline = new AfPipeline(makePassExecutor());
      const r1 = await pipeline.execute(makeInput('T-E2E-A'));
      const r2 = await pipeline.execute(makeInput('T-E2E-B'));

      expect(r1.isSuccess).toBe(true);
      expect(r2.isSuccess).toBe(true);
      // Both succeeded; enrichedInput taskType differs
      expect(r1.data!.enrichedInput.taskType).toBe('T-E2E-A');
      expect(r2.data!.enrichedInput.taskType).toBe('T-E2E-B');
    });

    it('runCount increments after each execution', async () => {
      const pipeline = new AfPipeline(makePassExecutor());
      expect(pipeline.runCount).toBe(0);
      await pipeline.execute(makeInput());
      expect(pipeline.runCount).toBe(1);
      await pipeline.execute(makeInput());
      expect(pipeline.runCount).toBe(2);
    });
  });
});
