/**
 * PhaseRequirementsSeeder — FLOW-37 Phase A bootstrap
 *
 * Manual bootstrap only (per bootstrap-boundary contract).
 * Phase A creates the components that cannot be generated by a flow topology
 * because they are prerequisites for flow topologies to run at all.
 *
 * What it creates:
 *   1. Phase requirement documents in xiigen-phase-requirements
 *      (one per FLOW-37 phase: A through F)
 *   2. 5 FLOW_DESIGN RAG seeds in xiigen-rag-patterns
 *      (teach future convergence runs about FLOW-37 design constraints)
 *
 * DNA-3: returns DataProcessResult<T>, never throws.
 * DNA-8: storeDocument before any emit.
 * DNA-5: tenantId from ALS — not passed to fabric methods.
 */

import { Injectable, Inject, Logger } from '@nestjs/common';
import { IDatabaseService, DATABASE_SERVICE } from '../../../fabrics/interfaces/database.interface';
import { DataProcessResult } from '../../../kernel/data-process-result';
import { MASTER_TENANT_ID } from '../../../bootstrap/bootstrap-seeder.service';

const PHASE_REQ_INDEX = 'xiigen-phase-requirements';
const RAG_INDEX = 'xiigen-rag-patterns';

const FLOW37_PHASES = [
  {
    phaseId: 'PHASE-A',
    requirements: {
      description: 'Bootstrap — create indices and seed requirements. No AI. No topology.',
      prerequisites: [],
      outputs: [
        'xiigen-phase-requirements index',
        '5 FLOW_DESIGN RAG seeds',
        'phase-capability-gate topology contract',
      ],
    },
  },
  {
    phaseId: 'PHASE-B',
    requirements: {
      description: 'Generate phase-capability-gate topology via cycle-chain/run.',
      prerequisites: ['PHASE-A complete', 'FLOW-36 ACTIVE'],
      outputs: [
        'PhaseCapabilityGateService',
        'DPO triples',
        'CYCLE-4 PENDING_IMPLEMENTATION record',
      ],
    },
  },
  {
    phaseId: 'PHASE-C',
    requirements: {
      description: 'Generate StackCouplingAuditor (T590) via cycle-chain/run.',
      prerequisites: ['PHASE-B complete', 'phase-capability-gate deployed'],
      outputs: ['StackCouplingAuditor service (T590)', 'coupling-audit DPO triples'],
    },
  },
  {
    phaseId: 'PHASE-D',
    requirements: {
      description: 'Generate HybridGenesisPromptBuilder (T591) via cycle-chain/run.',
      prerequisites: ['PHASE-C complete', 'T590 deployed'],
      outputs: ['HybridGenesisPromptBuilder service (T591)'],
    },
  },
  {
    phaseId: 'PHASE-E',
    requirements: {
      description: 'Stub replacement — apply STACK_IMPLEMENTATIONS to FLOW-01..34 genesis prompts.',
      prerequisites: ['PHASE-D complete', 'T590 + T591 deployed'],
      outputs: ['Updated genesis prompts with STACK_IMPLEMENTATIONS substitution'],
    },
  },
  {
    phaseId: 'PHASE-F',
    requirements: {
      description:
        'Integration validation — verify no INCOMPATIBLE combinations remain undetected.',
      prerequisites: ['PHASE-E complete'],
      outputs: ['BFA validation report', 'CF-799 compliance confirmed'],
    },
  },
];

const FLOW37_RAG_SEEDS = [
  {
    patternId: 'FLOW-37-DESIGN-001',
    patternType: 'FLOW_DESIGN',
    flowId: 'FLOW-37',
    teachingPoint:
      'Engine self-awareness requires reading from xiigen-phase-requirements before any topology runs — this index must be seeded in Phase A, not generated by the topology itself. The topology is a consumer of phase requirements, not a producer.',
    positiveExample:
      '// Phase A: seed documents to xiigen-phase-requirements\n// Phase B+: topology reads this index as prerequisite data',
    negativeExample:
      '// WRONG: topology generates phase requirements on first run\n// This creates a circular dependency — topology cannot run without the data it produces',
    tags: ['engine-self-awareness', 'bootstrap-boundary', 'phase-requirements'],
    connectionType: 'FLOW_SCOPED',
    tenantId: MASTER_TENANT_ID,
  },
  {
    patternId: 'FLOW-37-DESIGN-002',
    patternType: 'FLOW_DESIGN',
    flowId: 'FLOW-37',
    teachingPoint:
      'Capability gap detection (FLOW-37 capability gate) reads FT records from xiigen-feature-registry. The gate evaluates portingCandidate flags. If FLOW-36 has not run first, the gate has no data to evaluate.',
    positiveExample:
      '// Prerequisite check: verify FLOW-36 ACTIVE before running phase gate\n// FT records must exist before portingCandidate evaluation',
    negativeExample:
      '// WRONG: run phase gate without checking FLOW-36 status\n// Result: empty FT record pool → gate evaluates nothing → false PASS',
    tags: ['engine-self-awareness', 'capability-gap', 'feature-registry-dependency'],
    connectionType: 'FLOW_SCOPED',
    tenantId: MASTER_TENANT_ID,
  },
  {
    patternId: 'FLOW-37-DESIGN-003',
    patternType: 'FLOW_DESIGN',
    flowId: 'FLOW-37',
    teachingPoint:
      'Phase gate evaluation must distinguish between: (a) phase not yet run (no record), (b) phase running (status=IN_PROGRESS), and (c) phase failed (status=FAILED). A missing record and a FAILED record have different remediation paths.',
    positiveExample:
      '// getDocument returns NOT_FOUND → phase not yet started → queue bootstrap\n// getDocument returns status=FAILED → phase previously failed → inspect error before retry',
    negativeExample:
      '// WRONG: treat NOT_FOUND and FAILED as the same case\n// Missing record is a first-run condition; FAILED record requires diagnosis',
    tags: ['engine-self-awareness', 'phase-gate-evaluation', 'status-discrimination'],
    connectionType: 'FLOW_SCOPED',
    tenantId: MASTER_TENANT_ID,
  },
  {
    patternId: 'FLOW-37-DESIGN-004',
    patternType: 'FLOW_DESIGN',
    flowId: 'FLOW-37',
    teachingPoint:
      'Design flaw signals from the coupling audit (T590) must be stored as GAP_SIGNAL records in xiigen-capability-gap-signals before any downstream notification. Emitting a queue event without storing the signal violates DNA-8 and loses signal history if the consumer fails.',
    positiveExample:
      '// storeDocument(gap-signal) → emit(capability.gap.detected)\n// If consumer fails: replay from xiigen-capability-gap-signals',
    negativeExample:
      '// WRONG: emit(capability.gap.detected) without storeDocument\n// If consumer fails: signal is permanently lost',
    tags: ['engine-self-awareness', 'design-flaw-signal', 'dna-8'],
    connectionType: 'FLOW_SCOPED',
    tenantId: MASTER_TENANT_ID,
  },
  {
    patternId: 'FLOW-37-DESIGN-005',
    patternType: 'FLOW_DESIGN',
    flowId: 'FLOW-37',
    teachingPoint:
      'The read-back loop from FLOW-38 closes at FLOW-37: convergence context for FLOW-37 task types retrieves RAG patterns from xiigen-rag-patterns. These seeds (FLOW-37-DESIGN-001..005) are the starting prior art. The first time FLOW-37 runs through cycle-chain, these seeds inform the NODE generation prompts.',
    positiveExample:
      '// convergence.handler retrieves FLOW_DESIGN patterns for FLOW-37 archetype\n// Seeds present → context package contains prior art → providers have domain-specific material to disagree about',
    negativeExample:
      '// No seeds → context package is generic DNA rules only\n// Round 1 convergence → NOISE_SIGNAL DPO triple → no curriculum value',
    tags: ['engine-self-awareness', 'rag-read-back', 'convergence-context'],
    connectionType: 'FLOW_SCOPED',
    tenantId: MASTER_TENANT_ID,
  },
];

export interface SeedResult {
  phaseRequirementsSeeded: number;
  ragPatternsSeeded: number;
}

@Injectable()
export class PhaseRequirementsSeeder {
  private readonly logger = new Logger(PhaseRequirementsSeeder.name);

  constructor(@Inject(DATABASE_SERVICE) private readonly db: IDatabaseService) {}

  async seed(): Promise<DataProcessResult<SeedResult>> {
    try {
      let phaseRequirementsSeeded = 0;
      let ragPatternsSeeded = 0;

      // Seed phase requirement documents — DNA-8: storeDocument first
      for (const phase of FLOW37_PHASES) {
        const doc: Record<string, unknown> = {
          id: `FLOW-37-${phase.phaseId}`,
          flowId: 'FLOW-37',
          phaseId: phase.phaseId,
          requirements: phase.requirements,
          status: 'NOT_STARTED',
          connectionType: 'FLOW_SCOPED',
          tenantId: MASTER_TENANT_ID,
          createdAt: new Date().toISOString(),
        };
        const result = await this.db.storeDocument(
          PHASE_REQ_INDEX,
          doc,
          `FLOW-37-${phase.phaseId}`,
        );
        if (result.isSuccess) {
          phaseRequirementsSeeded++;
        } else {
          this.logger.warn(
            `PhaseRequirementsSeeder: failed to seed ${phase.phaseId}: ${result.errorMessage ?? 'unknown'}`,
          );
        }
      }

      // Seed RAG patterns — DNA-8: storeDocument, no emit needed for seeds
      for (const seed of FLOW37_RAG_SEEDS) {
        const result = await this.db.storeDocument(
          RAG_INDEX,
          { ...seed, createdAt: new Date().toISOString() } as Record<string, unknown>,
          seed.patternId,
        );
        if (result.isSuccess) {
          ragPatternsSeeded++;
        } else {
          this.logger.warn(
            `PhaseRequirementsSeeder: failed to seed ${seed.patternId}: ${result.errorMessage ?? 'unknown'}`,
          );
        }
      }

      this.logger.log(
        `PhaseRequirementsSeeder: complete — phaseRequirements=${phaseRequirementsSeeded} ragPatterns=${ragPatternsSeeded}`,
      );
      return DataProcessResult.success({ phaseRequirementsSeeded, ragPatternsSeeded });
    } catch (err) {
      return DataProcessResult.failure(
        'SEEDER_ERROR',
        `PhaseRequirementsSeeder threw: ${String(err)}`,
      );
    }
  }
}
